- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetConfig.kt
> DROID-1615 Main | Widgets | Add possibility to use local recent

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/navigation/PageLinksAdapter.kt
- core-ui/src/main/res/values/strings.xml
> DROID-1615 Main | Widgets | Change the sources descriptions

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/text/TextInputWidget.kt
---
---
Fixes #279 
https://github.com/anyproto/anytype-kotlin/assets/69634269/753be5a5-1a0a-4fd4-9044-499b8c51d835
> DROID Editor | Fix | Fix IME suggestions

- core-ui/src/test/java/com/anytypeio/anytype/core_ui/BlockAdapterTest.kt
> DROID-1574 Editor | Fix | Fixed broken tests

- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/Subscription.kt
> DROID-1697 Multispaces | Fix | Fix search filters for fullscreen widgets

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetCreateBookmarkRecordDI.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/objects/CreateBookmarkObject.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetCreateBookmarkRecordViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- versioning.gradle
> DROID-1697 Multispaces | Tech | Fix flow for creating new object in data view

- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileFragment.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileViewModel.kt
- versioning.gradle
> DROID-1697 Multispaces | Tech | Show error toast when failed to delete account

- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
> DROID-1722 Widgets | Fix | Apply object order for the current view of the collection widgets

- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperMapper.kt
> DROID-1725 Library | Fix |  Ensure unique keys for library views

- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileFragment.kt
> DROID-1718 Settings | Fix | Adapt media permission for android 33 on profile screen

- app/src/main/java/com/anytypeio/anytype/di/feature/SplashDi.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SelectSpaceDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/SelectSpaceFragment.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsCache.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsDataRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/LaunchAccount.kt
- domain/src/main/java/com/anytypeio/anytype/domain/base/Resultat.kt
- domain/src/main/java/com/anytypeio/anytype/domain/config/UserSettingsRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/spaces/SaveCurrentSpace.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultUserSettingsCache.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SelectSpaceViewModel.kt
> DROID-1758 Multispaces | Fix | Restore last selected space across app restart

- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
> DROID-1750 Widgets | Fix | Introduce mutex to prevent concurrent modification issue in tree widget container

- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
> DROID-1757 Widgets | Fix | Filter out archived or deleted favorite objects in tree or list widgets

- gradle/libs.versions.toml
Integrate https://github.com/anyproto/anytype-heart/releases/tag/v0.28.7
> DROID-1775 Protocol | Enhancement |  MW 0.28.7

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
> DROID-1699 Widgets | Enhancement | Show data view tabs only if set or collection has more than one view tab

- core-models/src/main/java/com/anytypeio/anytype/core_models/WidgetSession.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
> DROID-1778 Multispaces | Enhancement | Collapsed widget state should be saved and restored when restarting the app or switching between spaces.

- app/src/main/java/com/anytypeio/anytype/di/feature/AuthDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/home/HomescreenDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/signup/OnboardingSoulCreationAnimDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/signup/OnboardingVoidDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/settings/FilesStorageDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/settings/MainSettingsDi.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/settings/ProfileDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/Icons.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Block.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/other/Title.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconWidget.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RadialGradientComposeView.kt
- core-ui/src/main/res/layout/item_block_title_profile.xml
- core-ui/src/main/res/layout/widget_object_icon.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/model/BlockView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/linking/LinkToObjectOrWebViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceGradientProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/TreeWidgetContainerTest.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/main/MainSettingScreen.kt
> DROID-1643 App | Enhancement | Display space gradient for profile icon if it is set as icon option — in search, widgets, editor, etc.

- app/src/main/res/layout/fragment_viewer_relations_list.xml
> DROID-1587 View | Fix | Text style

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-1885 Protocol | MW 0.29.3

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerEditWidget.kt
> DROID-1815 Data View | Fix | Design fixes

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewersWidget.kt
> DROID-1872 Data View | Fix | Invalid Views Widget screen behavior 

- app/src/main/java/com/anytypeio/anytype/other/MediaPermissionHelper.kt
- app/src/main/java/com/anytypeio/anytype/ui/auth/account/CreateAccountFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/PickerDelegate.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/cover/SelectCoverGalleryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/modals/IconPickerFragmentBase.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationStatusValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationValueBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationValueDVFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileFragment.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/const/FileConstants.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/FilePickerUtils.kt
- gradle/libs.versions.toml
> DROID-1760 Tech | Fix | Unable to upload a picture or video

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-1896 Editor | Fix | Change type to Set

- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectSetMenuViewModel.kt
> DROID-1717 Analytics | Fix | Added type param to "duplicate" event

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-1900 Tech | MW 0.29.6

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerEditWidget.kt
> DROID-1870 View | Fix | Cursor color fix

- gradle/libs.versions.toml
> DROID-1905 Tech | MW 0.29.7

- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-1847 Analytics | Templates events fixes

- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/TemplateBlankMenuFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/templates/TemplateSelectFragment.kt
- app/src/main/res/layout/fragment_template_blank_menu.xml
- core-ui/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/TemplateSelectViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorMenuTest.kt
> DROID-1650 Templates |  Default template for new object creation, fixes

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-1910 Type | Fix | Crash on object type change 

- app/src/androidTest/java/com/anytypeio/anytype/features/editor/base/EditorTestSetup.kt
- app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- domain/src/main/java/com/anytypeio/anytype/domain/templates/GetTemplates.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/delegates/LibraryTypesDelegate.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/delegates/MyTypesDelegate.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/moving/MoveToViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/CreateObjectOfTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeChangeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/Subscriptions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/ObjectTypeTemplatesContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/TemplateView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/types/ObjectTypeChangeViewModelTest.kt
> DROID-1898 Templates | Fix | Blank state after tapping the New+ button

- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/debugging/DebugGoroutines.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-1921 Tech | Integrate Debug Goroutines use case

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectMenuDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- app/src/main/res/layout/fragment_object_menu.xml
- core-ui/src/main/res/drawable/ic_object_menu_debug_goroutines.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Orchestrator.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectSetMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/util/downloader/DebugGoroutinesShareDownloader.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/util/downloader/MiddlewareShareDownloader.kt
> DROID-1921 Tech | Integrate StackGoroutines, added to the menu

- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- middleware/src/main/res/values/strings.xml
> DROID-1897 Template | Fix | Make template from objects, text fix

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/AddDataViewRelationObjectValueDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/AddObjectRelationValueDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectRelationValueDi.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/ObjectRelationListFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationValueDVFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/add/AddObjectRelationFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/add/AddOptionsRelationDVFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/add/BaseAddOptionsRelationViewModel.kt
> DROID-1761 Relations | Fix | Relations are duplicated in DataView

- app/src/main/java/com/anytypeio/anytype/di/feature/relations/LimitObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/LimitObjectTypeFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/LimitObjectTypeViewModel.kt
> DROID-1958 Relations | Fix | Fix broken limit-object-type-picker screen

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-1949 Templates | Fix | Templates disappear in the collection after selecting a type

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ViewerEditWidgetUi.kt
> DROID-1964 View | Fix | Relations done and name 

- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModel.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/SegmentLine.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/SpaceStorageScreen.kt
> DROID-1886 Multispaces | Fix |  Remote storage, colors

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SearchRelationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/filter/FilterViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/filter/ViewerFilterViewModel.kt
> DROID-1971 Relations | Fix | Values for formats objects are missing

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectCreateTest.kt
> DROID-1948 Tests | Fix | Fix create objects in sets tests

- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/delegates/LibraryRelationsDelegate.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/delegates/MyRelationsDelegate.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationAddViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/anytypeio/anytype/presentation/relations/RelationAddViewModelBaseTest.kt
> DROID-1974 Library |Fix | Restrict the deletion of relations in the library

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectSetMenuViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorMenuTest.kt
> DROID-1977 Object | Fix | Human objects deletion is restricted

- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/CreateObjectOfTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/CreateObjectOfTypeScreen.kt
- app/src/main/res/values/strings.xml
- domain/src/main/java/com/anytypeio/anytype/domain/workspace/AddObjectToWorkspace.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/CreateObjectOfTypeViewModel.kt
> DROID-1925 Types | Enhancement | Suggest Anytype Library types within new object creation UX

- app/src/main/java/com/anytypeio/anytype/ui/settings/RemoteFilesManageFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/remote/RemoteFilesManageScreen.kt
> DROID-1915 Design | Fix | Settings, Incorrect display of the design

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-1933 Set | Fix | Unexpected layout toast

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-1948 Templates | Fix | The type from Anytype Library in the set is not applied immediately

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/DataViewViewState.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionAddRelationTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateCollectionViewTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateSetViewTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/objects/ObjectTypeExtensionsKtTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetDataViewObjectCreateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/CollectionViewerTypeAndTemplateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/SetByRelationViewerTypeAndTemplateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/SetByTypeViewerTypeAndTemplateTest.kt
> DROID-1975 Set | Fix | Restrict creating objects in a set by media formats

- app/src/main/java/com/anytypeio/anytype/ui/templates/TemplateBlankFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/TemplateBlankViewModel.kt
> DROID-1650 Template | Fix | Blank template state

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-1948 Templates | Fix | Update types in widget

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
> DROID-1941 Templates | Fix | Remove plus button from drop down menu

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuOptionsProviderImpl.kt
> DROID-1994 Video object | Fix | Crash after open settings menu

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/subscription/DataViewSubscription.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateSetViewTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetConvertToCollectionTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
> DROID-1972 Navigation | Fix | Set-to-set navigation

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerEditMoreMenu.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerLayoutListMenu.kt
> DROID-1871 Design | Ppdate background for context menus

- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/CreateObjectOfTypeScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/CreateObjectOfTypeViewModel.kt
> DROID-1769 Design | New object creation widget

- localization/src/main/res/values/strings.xml
> DROID-2008 Design | Rename add link button

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectTypeIds.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-1706 Analytics | Object type property

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/subscription/DataViewSubscription.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateSetViewTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetConvertToCollectionTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
> DROID-1972 Navigation | Fix | Set to set navigation

- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionAddRelationTest.kt
> DROID-1108 Data View | Fix | Design fixes for gallery view , test

- app/src/main/java/com/anytypeio/anytype/ui/settings/system/PreferenceFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/NetworkModeConstants.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/networkmode/NetworkModeProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/PreferencesViewModel.kt
> DROID-1602 Self-hosting | App Preference Screen

- gradle/libs.versions.toml
> DROID-2040 Protocol | Enhancement | MW 0.29.17

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2021 Backlink | Fix | Add as link to collection

- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationValueBaseFragment.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationValueBaseViewModel.kt
> DROID-2043 Backlinks | Fixes

- app/src/main/java/com/anytypeio/anytype/di/feature/AddFileRelationDi.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/FileActionsFragment.kt
- app/src/main/res/layout/fragment_relation_file_value_action.xml
- core-ui/src/main/res/drawable/ic_variant_empty.xml
- core-ui/src/main/res/drawable/ic_variant_selected.xml
- core-ui/src/main/res/drawable/ic_variant_selector.xml
- core-ui/src/main/res/drawable/rounded_rectangle_data_view_action.xml
- core-ui/src/main/res/layout/item_edit_cell_file.xml
- core-ui/src/main/res/values/styles.xml
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/const/MimeTypes.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/add/AddFileRelationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationValueBaseViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/relations/RelationExtensionsTest.kt
> DROID-1838 Relations | Fix | Adding files to relations, pt. 2

- app/src/main/res/layout/fragment_editor.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/ObjectTypesComposeWidget.kt
> DROID-2046 Design | New change type menu does not have top space

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/DefaultBlockViewRendererTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorFeaturedRelationsTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorPresentationTestSetup.kt
> DROID-2043 Objects | Backlinks | Hide, when value is empty 

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/page/CreateObject.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2052 Create objets | Fix | Navigation to sets

- app/src/main/java/com/anytypeio/anytype/ui/relations/add/AddFileRelationFragment.kt
- app/src/main/res/layout/fragment_relation_object_value_add.xml
- app/src/main/res/layout/fragment_relation_value_file_add.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-1838 Relations | Fix | Add file screen design fixes

- gradle/libs.versions.toml
> DROID-2064 Protocol | Enhancement | MW 0.30.0-rc7

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/GalleryViewContentWidget.kt
> DROID-1108 Data view | Fix |  Fix gallery view card bottom margin

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ResExtension.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/StatusBadgeWidget.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/sync/SyncStatusView.kt
> DROID-2020 Self-host | Fix | Sync status local 

- .gitignore
- core-models/src/main/java/com/anytypeio/anytype/core_models/NetworkMode.kt
- presentation/build.gradle
- presentation/src/main/java/com/anytypeio/anytype/presentation/sync/SyncStatusView.kt
> DROID-1602 Self hosting | Fix | Network mode config

- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2066 Templates | Fix | Default template doesn't apply

- app/build.gradle
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/CreateObjectOfTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/CreateObjectOfTypeScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/CreateObjectOfTypeViewModel.kt
> DROID-1922 Type screen | Fix | User interaction and screen state

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/CreateObjectOfTypeFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/CreateObjectOfTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2050 Create Object | Fix | Restricted changing type to a collection or set in an object

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
> DROID-1744 Analytics | Fix | Send link event

- gradle/libs.versions.toml
> DROID-2086 Protocol | Enhancement | MW 0.30.0

- gradle/libs.versions.toml
> DROID-2091 Protocol | Enhancement | MW 0.30.1

- domain/src/main/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObject.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockCollection.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectCreateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateCollectionViewTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetDataViewObjectCreateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/CollectionViewerTypeAndTemplateTest.kt
> DROID-2079 Collection | Prefilled objects

- app/src/main/java/com/anytypeio/anytype/ui/editor/PickerDelegate.kt
> DROID-2107 File picker | Crash

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt
- domain/src/main/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObject.kt
- domain/src/test/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObjectUseCaseTest.kt
> DROID-2079 DataView | Fix | Prefill details for new object

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-2115 Protocol | Integrate 0.30.4

- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
> DROID-2115 Protocol | Integrate 0.30.4, fix request

- app/src/androidTest/java/com/anytypeio/anytype/features/relations/ObjectRelationDateValueTest.kt
- app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/EditGridCellDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/UtilModule.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationDateValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/modals/DatePickerFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/misc/DateProvider.kt
- domain/src/test/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObjectUseCaseTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationDateValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImpl.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockCollection.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockSet.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectCreateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/RelationDateValueViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetDataViewObjectCreateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/SetByRelationTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/CollectionViewerTypeAndTemplateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/SetByRelationViewerTypeAndTemplateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/SetByTypeViewerTypeAndTemplateTest.kt
> DROID-1018 Sets or Collections | Fix | 'Due date is today' filter only shows tasks which are due tomorrow

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/Markup.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/text/MentionSpan.kt
- core-ui/src/test/java/com/anytypeio/anytype/core_ui/features/editor/BlockAdapterReadWriteModeTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/mention/MentionExt.kt
> DROID-1759 Editor | Fix | Mention is not renamed

- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
> DROID-1839 Analytics | Media blocks events

- app/src/main/java/com/anytypeio/anytype/di/feature/objects/SelectObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/DataModule.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/SelectObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/SelectObjectTypeScreen.kt
- app/src/main/res/values/strings.xml
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsCache.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsDataRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/base/Interactor.kt
- domain/src/main/java/com/anytypeio/anytype/domain/config/UserSettingsRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/types/GetPinnedObjectTypes.kt
- domain/src/main/java/com/anytypeio/anytype/domain/types/SetPinnedObjectTypes.kt
- domain/src/main/java/com/anytypeio/anytype/domain/wallpaper/RestoreWallpaper.kt
- gradle/libs.versions.toml
- persistence/build.gradle
- persistence/src/main/java/com/anytypeio/anytype/persistence/preferences/Preferences.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultAuthCache.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultUserSettingsCache.kt
- persistence/src/main/proto/preferences.proto
- persistence/src/test/java/com/anytypeio/anytype/persistence/UserSettingsCacheTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SelectObjectTypeViewModel.kt
> DROID-2146 Objects | Enhancement | Allow pinning and unpinning types in the new object-creation panel

- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ui/BaseFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/ext/BlockViewExt.kt
> DROID-1911 App | Tech | FIx crashes during navigation + clean up sentry logs

- domain/src/main/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObject.kt
- domain/src/test/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObjectUseCaseTest.kt
> DROID-2079 Set | Fix | Proper type of prefilled timestamp

- gradle/libs.versions.toml
- protocol/src/main/proto/localstore.proto
> DROID-2165 Protocol | Enhancement | MW 0.30.11

- localization/src/main/res/values/strings.xml
> DROID-2163 Onboarding | Fix | Renaming

- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/SelectObjectTypeScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/SearchField.kt
> DROID-2121 Relations | Move search field to core ui

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-2135 Files as objects | Pr update

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/EditorDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/TagStatusDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/TagStatusFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/RelationsLazyList.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/TagItem.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagStatusViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagStatusViewModelFactory.kt
> DROID-2121 Relations | Tag, status screen

- app/src/main/java/com/anytypeio/anytype/di/feature/TagStatusDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/DeleteOptionWarningFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/TagOrStatusValueFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Warnings.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/TagOrStatusCompose.kt
- core-ui/src/main/res/values/strings.xml
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/relations/DeleteRelationOptions.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModelFactory.kt
> DROID-2121 Relations | Empty state, delete option

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RelationValueListWidget.kt
- core-ui/src/main/res/drawable/ic_checkbox_checked.xml
- core-ui/src/main/res/drawable/ic_checkbox_unchecked.xml
- core-ui/src/main/res/layout/relation_value_list.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetRenderMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationObjectExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SetsExtension.kt
> DROID-2122 Relations | Fix | Design fixes

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/OptionDi.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/TagStatusDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/ObjectRelationListFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/CreateOrEditOptionFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/TagOrStatusValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetCommand.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetNavigationTest.kt
> DROID-2121 Relations | Tag and status, integration

- app/src/main/java/com/anytypeio/anytype/ui/relations/value/TagOrStatusValueFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
> DROID-2121 Relations | Sorting tags

- app/src/main/java/com/anytypeio/anytype/ui/sharing/Sharing.kt
- app/src/main/java/com/anytypeio/anytype/ui/sharing/SharingFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Response.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- device/src/main/java/com/anytypeio/anytype/device/SharedFileUploader.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/GetLastOpenedObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/cover/SetDocCoverImage.kt
- domain/src/main/java/com/anytypeio/anytype/domain/device/FileSharer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetDocumentImageIcon.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetTextBlockImage.kt
- domain/src/main/java/com/anytypeio/anytype/domain/media/UploadFile.kt
- domain/src/main/java/com/anytypeio/anytype/domain/relations/AddFileToObject.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/test/java/com/anytypeio/anytype/MiddlewareTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sharing/AddToAnytypeViewModel.kt
> DROID-2072 Sharing extension | Enhancement | Display filename in the content field

- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/LaunchAccount.kt
- domain/src/main/java/com/anytypeio/anytype/domain/workspace/WorkspaceManager.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SelectSpaceViewModel.kt
> DROID-2195 Multispaces | Tech | Safer set-space operations

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/AttachmentValueDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/EditorDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectValueDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/AttachmentValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/value/ObjectValueFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/attachment/AttachmentValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/attachment/AttachmentValueViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModelFactory.kt
> DROID-1960 Relations | Attachment and object value screens

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/Icons.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
> DROID-2123 Tech | Moving compose icons 

- domain/src/main/java/com/anytypeio/anytype/domain/workspace/WorkspaceManager.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/linking/LinkToObjectOrWebViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/linking/LinkToObjectViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/add/AddObjectRelationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2123 Tech | Get spaces extension

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/SelectSpaceScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/Icons.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconWidget.kt
- core-ui/src/main/res/drawable/circle_default_avatar_background.xml
- core-ui/src/main/res/drawable/circle_profile_icon.xml
- core-ui/src/main/res/drawable/object_in_list_background_profile_initial.xml
> DROID-2189 Objects | Design | Change profile placeholder background

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/modals/IconPickerFragmentBase.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/modals/ObjectIconPickerFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/SelectSpaceFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetDocumentImageIcon.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetImageIcon.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetTextBlockImage.kt
- domain/src/main/java/com/anytypeio/anytype/domain/object/OpenObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/relations/AddFileToObject.kt
- middleware/src/test/java/com/anytypeio/anytype/MiddlewareTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Store.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/picker/ObjectIconPickerViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/picker/IconPickerViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetCommand.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationValueBaseViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SelectSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/types/icon_picker/TypeIconPickerViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorMenuTest.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileSettingsViewModel.kt
> DROID-2195 Multispaces | Tech | Always provide space id when uploading file

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectType.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ResExtension.kt
- gradle/libs.versions.toml
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectLayoutView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuOptionsProviderImpl.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/mention/MentionExtKtTest.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-2212 Protocol | Enhancement | MW 0.32.0-rc2

- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
> DROID-2121 Relation | Fix | Create status

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
> DROID-2187 Multispaces | Tech |  Support participant layout

- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationDateValueFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
- core-ui/src/main/res/values/colors.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationDateValueViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetCellTest.kt
> DROID-2125 Relations | Date editable state

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/ObjectRelationListFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectValueCompose.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/StatusItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/TagItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/TagOrStatusCompose.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/LockedStateProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
> DROID-2125 Relations | Editable state

- gradle/libs.versions.toml
- protocol/src/main/proto/models.proto
> DROID-2216 Protocol | Enhancement | MW 0.32.0-rc3

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-2223 MW | Protocol 0.30.14

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/listener/ListenerType.kt
> DROID-2187 Objects | Fix | Open objects with participant layout from link or from mention

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectValueDI.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ItemMenu.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectValueCompose.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROIS-2124 Relations | Objects value, fixes

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeChangeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuOptionsProviderImpl.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/types/ObjectTypeChangeViewModelTest.kt
> DROID-2201 File as Object | Support file visibility set

- gradle/libs.versions.toml
> DROID-2230 Tech | MW 0.30.15

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectType.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/mention/MentionExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationValueBaseViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2234 Multiplayer | Fix | Allow opening participant object from sets or collections

- gradle/libs.versions.toml
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/mention/MentionExtKtTest.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2244 Protocol | Enhancement | MW 0.32.0-rc6

- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2030 Analytics | Property type for screenset and screencollection

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectItem.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2123 Relations | Object menu, restrictions

- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingNetworkSetupDialog.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signin/OnboardingNetworkSetupScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-2113 Settings | Fix | Add yamux config toggle

- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
> DROID-2135 FaO | Fix | Missing space id

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/ObjectTypesComposeWidget.kt
- core-ui/src/main/res/drawable/ic_arrow_up_18.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-2180 Design | Update select type menu above keyboard in editor

- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-2262 Multiplayer | Tech | Basic API for space sharing

- app/src/main/java/com/anytypeio/anytype/di/feature/multiplayer/ShareSpaceInject.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/multiplayer/Multiplayer.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Inviting.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- core-ui/src/main/res/drawable/ic_space_widget_share_space_icon.xml
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/GenerateSpaceInviteLink.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
> DROID-2264 Multiplayer | Enhancement | Basic UX for generating space invite link

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-2267 FaO | Fix |  Support block restrictions for file objects

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerEditWidget.kt
> DROID-2017 Data view | Design | Edit view widget 

- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Inviting.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/System.kt
- core-ui/src/main/res/values/strings.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-2256 Multiplayer | Design | Share-space screen layout basics

- app/src/main/java/com/anytypeio/anytype/di/feature/multiplayer/ShareSpaceInject.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/multiplayer/Multiplayer.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- core-ui/src/main/res/values/strings.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2256 Multiplayer | Tech | Fetch space members list for share-space screen

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- app/src/main/res/layout/fragment_object_set.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/SetTitleWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-1212 Set | Title bottom widget

- gradle/libs.versions.toml
- protocol/src/main/proto/models.proto
> DROID-2268 Protocol | Enhancement | MW 0.32.0-rc7

- gradle/libs.versions.toml
> DROID-2270 Tech | MW 0.32.0-rc8

- domain/src/main/java/com/anytypeio/anytype/domain/spaces/GetSpaceViews.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SelectSpaceViewModel.kt
> DROID-2226 Multispaces | Fix | Fix space status filtering

- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Request.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/ApproveJoinSpaceRequest.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/DeclineSpaceJoinRequest.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/Alias.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2258 Multiplayer | Design | Layout for request-to-join-space -request screen + API requests

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RelationObjectItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RelationValueListWidget.kt
> DROID-2109 Relations | Fix | Untitled objects are not displayed in the relation

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ListViewMapper.kt
> DROID-2201 Sets or Collections | Fix | Support file visibility set

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/StatusItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/TagItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/TagOrStatusCompose.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
> DROID-2121 Relations | Fix | Tag value rendering fixes

- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/SpaceJoinRequestFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- core-ui/src/main/res/drawable/ic_dropdown_menu_check.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-2260 Multiplayer | Enhancement | Dropdown menu actions allowing to change member permissions + API calls

- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationDateValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/modals/DatePickerFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
> DROID-2125 Relations | Design fixes, date

- app/src/main/java/com/anytypeio/anytype/ui/library/views/list/items/Items.kt
> DROID-2266 Design | Library types, icon

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
> DROID-2194 Analytics | Fix | Fix route param

- app/src/main/AndroidManifest.xml
> DROID-2112 Self-hosting | Legacy screen

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
> DROID-2233 Multiplayer | Fix | Fix search filters related to 'Space member' type visibility

- domain/src/main/java/com/anytypeio/anytype/domain/search/RelationsSubscriptionManager.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationTextValueViewModel.kt
> DROID-2252 Relations | Fix | Relations search and relation blocks visibility

- gradle/libs.versions.toml
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorFeaturedRelationsTest.kt
> DROID-2290 Tech | Integrate MW 0.32.0

- app/src/main/java/com/anytypeio/anytype/ui/library/views/list/items/Items.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
- core-ui/src/main/res/values-night/colors.xml
- core-ui/src/main/res/values/colors.xml
> DROID-2125 Relations | Design | Date picker fixes

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-2299 Protocol | Enhancement | MW 0.32.1

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/number/NumberParser.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/relations/NumberParserTest.kt
> DROID-2298 Data view | Fix | Do not crash when failed to parse incorrect number format

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Request.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
> DROID-2176 Multiplayer | Design | Space member icons

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/text/TextInputWidget.kt
> DROID-2269 Editor | Fix | Wrong markup for numbers

- app/src/main/java/com/anytypeio/anytype/ui/spaces/CreateSpaceScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Space.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/multiplayer/Multiplayer.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/ApproveJoinSpaceRequest.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/ChangeSpaceMemberPermissions.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/SpaceWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
> DROID-2176 Multiplayer | Tech | Integrate spaceAccessType relation

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RelationValueListWidget.kt
> DROID-2122 Relations | Fix | Display only one value for multi-select fields

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
> DROID-2125 Relations | Design | Date picker, colors

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/Common.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
- core-ui/src/main/res/drawable/ic_checked_24.xml
> DROID-1960 Relations | Design | Icon and divider fixes

- Makefile
- scripts/mw/clean-protos.sh
- scripts/mw/update-mw.sh
> DROID-2324 App | Tech | Add clean-protos command to makefile

- app/src/main/java/com/anytypeio/anytype/ui/settings/space/SpaceSettingsFragment.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/main/MainSettingScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/Settings.kt
> DROID-2319 Multiplayer | Fix | Prevent space-icon editing and hide sections in read-only spaces

- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/screens/GalleryInstallationScreen.kt
- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/screens/GalleryInstallationSpacesScreen.kt
> DROID-1776 Gallery experience | Design | Main screens

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2203 FaO | Support file visibility in link to and mentions

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/MapExtension.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorMenuTest.kt
> DROID-2204 Editor | Fix | Link to files, name

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
> DROID-2330 Search | Fix | Limit global search results to 50 items for better performance

- app/src/main/java/com/anytypeio/anytype/ui/gallery/GalleryInstallationFragment.kt
- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/models/GalleryInstallationState.kt
- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/viewmodel/GalleryInstallationViewModel.kt
> DROID-1776 Gallery experience | Error handling

- app/src/main/java/com/anytypeio/anytype/ui/payments/PaymentsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Foundation.kt
- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/models/Tier.kt
- payments/src/main/java/com/anytypeio/anytype/screens/MembershipLevel.kt
- payments/src/main/java/com/anytypeio/anytype/viewmodel/PaymentsViewModel.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
> DROID-2274 Payment | Ui fixes

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/DataViewViewState.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> Droid 2314 Multiplayer | Enhancement | Data view in read-only spaces

- app/src/main/java/com/anytypeio/anytype/ui/gallery/GalleryInstallationFragment.kt
- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/models/GalleryInstallationState.kt
- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/viewmodel/GalleryInstallationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationsProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationsViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/NotificationsProviderTest.kt
> DROID-2307 Gallery experience | Gallery import notification + fixes

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-2362 Protocol | MW 0.33.0-rc6

- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2363 Multiplayer | Fix | Should propagate correct space id when opening sets from home screen

- gradle/libs.versions.toml
> DROID-2141 App | Tech | Update dependencies

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Space.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/multiplayer/Multiplayer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/workspace/WorkspaceManager.kt
- localization/src/main/res/values-de-rDE/strings.xml
- localization/src/main/res/values-es-rES/strings.xml
- localization/src/main/res/values-fr-rFR/strings.xml
- localization/src/main/res/values-in-rID/strings.xml
- localization/src/main/res/values-it-rIT/strings.xml
- localization/src/main/res/values-nl-rNL/strings.xml
- localization/src/main/res/values-no-rNO/strings.xml
- localization/src/main/res/values-pt-rBR/strings.xml
- localization/src/main/res/values-ru-rRU/strings.xml
- localization/src/main/res/values-uk-rUA/strings.xml
- localization/src/main/res/values-zh-rCN/strings.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/Settings.kt
> DROID-2315 Multiplayer | Fix | Rename personal space to default space

- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/main/Views.kt
> DROID-2319 Settings | Fix | Do not allow cutting or modifying space name text based on ACL

- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/StopSharingWarning.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-2376 Multiplayer | Enhancement | Show warning when attempting to stop space sharing

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/ObjectTopToolbar.kt
> DROID-2313 Editor | Fix | Three button visibility

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/ObjectTopToolbar.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/Mimetype.kt
> DROID-2353 Self-host | Fix | Select config file

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- gallery-experience/src/main/java/com/anytypeio/anytype/gallery_experience/viewmodel/GalleryInstallationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/CreateSpaceViewModel.kt
> DROID-2322 Gallery experience | Analytics

- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
> Self-host | Fix | Select config file, type missing

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2387 Protocol | Integrate 0.33.0-rc9

- app/src/main/java/com/anytypeio/anytype/other/Deeplinks.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- domain/src/main/java/com/anytypeio/anytype/domain/misc/DeepLinkResolver.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
> DROID-2393 Multiplayer | Enhancement | Parsing invite link from shared data

- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationObjectExtensions.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorFeaturedRelationsTest.kt
> DROID-2385 Relation | Global name for participant

- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
> DROID-2341 Multiplayer | Tech | Missing arguments

- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
> DROID-2364 Relations | Open links in one click

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RelationValueListWidget.kt
- localization/src/main/res/values-de-rDE/strings.xml
- localization/src/main/res/values-es-rES/strings.xml
- localization/src/main/res/values-fr-rFR/strings.xml
- localization/src/main/res/values-in-rID/strings.xml
- localization/src/main/res/values-it-rIT/strings.xml
- localization/src/main/res/values-nl-rNL/strings.xml
- localization/src/main/res/values-no-rNO/strings.xml
- localization/src/main/res/values-pt-rBR/strings.xml
- localization/src/main/res/values-ru-rRU/strings.xml
- localization/src/main/res/values-uk-rUA/strings.xml
- localization/src/main/res/values-zh-rCN/strings.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectRelationView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationObjectExtensions.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorFeaturedRelationsTest.kt
> DROID-2400 Backlinks | Links renaming

- app/src/main/java/com/anytypeio/anytype/di/feature/notifications/NotificationsDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/notifications/NotificationsFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/notifications/NotificationWidgets.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/notifications/OwnerNotifications.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationsViewModelFactory.kt
> DROID-2397 Multiplayer | Fix | Handle actions from space-join and space-leave notifications

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Request.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
> DROID-2345 Multiplayer | Disable buttons when reached restrictions

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/notifications/OwnerNotifications.kt
- localization/src/main/res/values-de-rDE/strings.xml
- localization/src/main/res/values-es-rES/strings.xml
- localization/src/main/res/values-fr-rFR/strings.xml
- localization/src/main/res/values-in-rID/strings.xml
- localization/src/main/res/values-it-rIT/strings.xml
- localization/src/main/res/values-nl-rNL/strings.xml
- localization/src/main/res/values-no-rNO/strings.xml
- localization/src/main/res/values-pt-rBR/strings.xml
- localization/src/main/res/values-ru-rRU/strings.xml
- localization/src/main/res/values-uk-rUA/strings.xml
- localization/src/main/res/values-zh-rCN/strings.xml
- localization/src/main/res/values/strings.xml
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/Settings.kt
> Droid 2176 Multiplayer | Fix | Design and wording fixes

- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipErrors.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipModels.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/payments/GetTiers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/Alias.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-2275 Payment |  Api

- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/MakeSpaceShareable.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-2257 Multiplayer | Tech | Add and call make-space-shareable command

- core-models/src/main/java/com/anytypeio/anytype/core_models/exceptions/SpaceLimitReachedException.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-2176 Multiplayer | Fix | Misc fixes

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/anytypeio/anytype/app/AndroidApplication.kt
- app/src/main/java/com/anytypeio/anytype/app/Notifications.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/MainEntryDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/NotificationsModule.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- domain/src/main/java/com/anytypeio/anytype/domain/notifications/SystemNotificationService.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModelFactory.kt
> DROID-2023 Multiplayer | Enhancement | Local system notification POF

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/anytypeio/anytype/app/Notifications.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/MainEntryDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- domain/src/main/java/com/anytypeio/anytype/domain/notifications/SystemNotificationService.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationActionDelegate.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationsViewModel.kt
> DROID-2023 Multiplayer | Enhancement | Handling actions from local system notifications

- app/src/main/java/com/anytypeio/anytype/di/feature/MainEntryDI.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModelFactory.kt
> DROID-2275 Membership | Fix | Di, missing params

- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2435 Protocol | Enhancement | MW 0.33.0-rc16

- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipModels.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-2435 Protocol | Enhancement | MW 0.33.0-rc16, fix protocol

- app/src/main/java/com/anytypeio/anytype/di/feature/home/HomescreenDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/ActiveSpaceMemberSubscriptionContainer.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/SpaceWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
> DROID-2441 Multiplayer | Enhancement | Show space members count in shared-space widget on home screen

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/localstore.proto
> DROID-2444 Protocol | MW, 0.33.0-rc17

- core-models/src/main/java/com/anytypeio/anytype/core_models/FileLimitsEvent.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/FileLimitsMiddlewareChannel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/FilesStorageViewModel.kt
> DROID-2436 Protocol | Support FileLimitsUpdated event

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2448 Protocol | MW, 0.33.0-rc18

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationObjectExtensions.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorFeaturedRelationsTest.kt
> DROID-2385 Editor | Relations globalName and identity

- gradle/libs.versions.toml
> DROID-2448 Protocol | MW, 0.33.0-rc20

- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/SpaceWidgetContainer.kt
> DROID-2441 Multiplayer | Fix | Fix space member count for space widget

- app/src/main/java/com/anytypeio/anytype/app/Notifications.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- app/src/main/java/com/anytypeio/anytype/ui/notifications/NotificationPermissionPromptDialog.kt
- app/src/main/res/navigation/graph.xml
- app/src/main/res/values/strings.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Warnings.kt
- domain/src/main/java/com/anytypeio/anytype/domain/notifications/SystemNotificationService.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
> DROID-2447 Multiplayer | Enhancement | Notification permission prompt

- app/src/main/java/com/anytypeio/anytype/di/feature/MainEntryDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- app/src/main/java/com/anytypeio/anytype/ui/splash/SplashFragment.kt
- app/src/main/res/values/strings.xml
- localization/src/main/res/values/strings.xml
- presentation/build.gradle
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
> DROID-2323 Multiplayer | Fix | Better deep-linking

- localization/src/main/res/values/strings.xml
> DROID-2457 Multiplayer | Fix | Rename "Default space" to "Entry space"

- app/src/main/AndroidManifest.xml
> DROID-2282 App | Tech | Added new deep links

- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipModels.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/membership/provider/MembershipProvider.kt
> DROID-2462 Protocol | MW, 0.33.0-rc22, fix

- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SpaceSettingsDI.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/ActiveSpaceMemberSubscriptionContainer.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/UserPermissionProviderStub.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/Settings.kt
> DROID-2368 Multiplayer | Enhancement | Show global name in space settings

- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
> DROID-2368 Multiplayer | Hotfix | Show global name in space settings

- app/src/main/java/com/anytypeio/anytype/other/Deeplinks.kt
- app/src/test/java/com/anytypeio/anytype/DefaultSpaceInviteResolverTest.kt
> DROID-2281 Multiplayer | Fix | Support old invite link format

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectValueDI.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/linking/LinkToObjectOrWebViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SetsExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
> DROID-2205 FaO | Fix | File icons and names

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SpaceListDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/MainComponent.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/CreateSpaceScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/SelectSpaceScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/SpaceListFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- app/src/main/res/navigation/graph.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/Spaces.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/SpaceListScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/System.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectValueCompose.kt
- core-ui/src/main/res/drawable/ic_settings_spaces.xml
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ui/ViewState.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/common/BaseViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceIconView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceListViewModel.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/fstorage/FilesStorageScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/main/MainSettingScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/main/Views.kt
> Droid 2332 Multiplayer | Feature | List of spaces with statuses

- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SpaceListDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/SpaceListFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/SpaceListScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Foundation.kt
- core-ui/src/main/res/drawable/ic_space_list_dots.xml
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/CancelJoinSpaceRequest.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/SpaceViewSubscriptionContainer.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceListViewModel.kt
> DROID-2332 Multiplayer | Enhancement | Added dropdown menu with actions on space-list screen

- domain/src/main/java/com/anytypeio/anytype/domain/spaces/GetSpaceViews.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sharing/AddToAnytypeViewModel.kt
> DROID-2156 Sharing extension | Fix | Sharing extension might not work correctly when app is not launched at the moment of sharing

- payments/src/main/java/com/anytypeio/anytype/payments/mapping/TierViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModel.kt
> DROID-2275 Membership | Tier mapping and name validating

- payments/src/test/java/com/anytypeio/anytype/payments/MembershipTestsSetup.kt
- payments/src/test/java/com/anytypeio/anytype/payments/PaymentsViewModelTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/StubMembership.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidNotActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierConditionInfoTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierNameTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierNotAndroidActiveAndFreeTests.kt
> DROID-2275 Membership | Tier states, tests

- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipResourcesExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/TierViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/TierView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/ConditionInfo.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierView.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActiveAndFreeTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActivePurchasedOniOSTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActivePurchasedOniOS.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierConditionInfoTests.kt
> DROID-2275 Membership | Tiers states

- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- gradle/libs.versions.toml
> DROID-2141 App | Tech | Update libs

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ViewerEditWidgetUi.kt
> DROID-2495 Sets or Collections | Fix | Incorrect order of applied relations in view settings

- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-2471 Multiplayer | Fix | Handle invite link to a deleted space

- app/src/main/java/com/anytypeio/anytype/di/feature/payments/PaymentsDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/payments/PaymentsFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipErrors.kt
- domain/src/main/java/com/anytypeio/anytype/domain/payments/GetMembershipEmailStatus.kt
- domain/src/main/java/com/anytypeio/anytype/domain/payments/SetMembershipEmail.kt
- domain/src/main/java/com/anytypeio/anytype/domain/payments/VerifyMembershipEmailCode.kt
- gradle/libs.versions.toml
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ErrorMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipResourcesExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/TierViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/TierView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/playbilling/BillingClientLifecycle.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/AnyNameView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/ConditionInfoView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/EnterCode.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/MembershipEmailScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/PaymentWelcomeScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipMainState.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModel.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModelFactory.kt
- payments/src/test/java/com/anytypeio/anytype/payments/MembershipTestsSetup.kt
- payments/src/test/java/com/anytypeio/anytype/payments/PaymentsViewModelTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActiveAndFreeTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
> DROID-2275 Membership | Email and name

- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipErrors.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Foundation.kt
- core-ui/src/main/res/values-night/colors.xml
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/TierViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/TierView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/AnyNameView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/EnterCode.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/PaymentWelcomeScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierPreviewScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModel.kt
> DROID-2275 Membership | Name validation 

- domain/src/main/java/com/anytypeio/anytype/domain/payments/SetMembershipEmail.kt
- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/screens/AnyNameView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/MembershipEmailScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModel.kt
> DROID-2488 Membership | Email verification fixes

- core-models/src/main/java/com/anytypeio/anytype/core_models/Block.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/Alias.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- middleware/src/test/java/com/anytypeio/anytype/MiddlewareTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
> DROID-2511 Protocol | MW 0.34.0-rc2

- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/models/TierView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
> DROID-2518 Membership | Terms of Use and Privacy Policy text

- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModel.kt
> DROID-2488 Membership | Fixes

- payments/src/main/java/com/anytypeio/anytype/payments/mapping/TierViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/TierView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/AnyNameView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/ConditionInfoPreview.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/ConditionInfoView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidNotActiveTests.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
> DROID-2513 Membership | Fix | Name already purchased

- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ui/BaseBottomSheetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2429 App | Fix | Release stabilisation

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-2529 Protocol | MW 0.34.0-rc3

- domain/src/main/java/com/anytypeio/anytype/domain/search/DataViewSubscriptionContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/subscription/DataViewSubscription.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockCollection.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockSet.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/CollectionViewerTypeAndTemplateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/SetByRelationViewerTypeAndTemplateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/templates/SetByTypeViewerTypeAndTemplateTest.kt
> DROID-2537 Sets | Tech | Update unsubscribe mechanism

- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipModels.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/TierViewExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/playbilling/BillingClientLifecycle.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/ConditionInfoView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/MainPaymensScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/PaymentsViewModel.kt
- payments/src/test/java/com/anytypeio/anytype/payments/MembershipTestsSetup.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActivePurchasedOniOSTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActivePurchasedOniOS.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierNewPurchaseTest.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
> DROID-2510 Membership | Fixes

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/localstore.proto
- protocol/src/main/proto/models.proto
> DROID-2541 Protocol | Enhancement | MW v0.34.0-rc5

- app/src/main/java/com/anytypeio/anytype/ui/payments/MembershipFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/DesignSystemButtons.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/DesignSystemDialogs.kt
- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/playbilling/BillingClientLifecycle.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipMainState.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipViewModel.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierBuilderFallbackOnExplorerTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/membership/provider/MembershipProvider.kt
> DROID-2493 Membership | Fixes

- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/test/java/com/anytypeio/anytype/payments/CocreatorActiveTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidNotActiveTests.kt
> DROID-2555 Membership | Fix | CoCreator tier 

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Foundation.kt
> DROID-2510 Membership | Legacy button state

- app/src/main/java/com/anytypeio/anytype/di/feature/settings/ProfileDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/Foundation.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/MembershipScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileSettingsViewModel.kt
> DROID-2525 Membership | Hide the membership menu in local only mode

- app/src/androidTest/java/com/anytypeio/anytype/features/sets/sort/ViewerObjectSortTest.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/Block.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/SpaceViewSubscriptionContainer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/spaces/GetSpaceViews.kt
- domain/src/main/java/com/anytypeio/anytype/domain/templates/GetTemplates.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/add/AddFileRelationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SelectSortRelationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/subscription/DataViewSubscription.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/ObjectTypeTemplatesContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/Subscription.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionDataViewUpdateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockCollection.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/ObjectSetReducerTest.kt
- test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/DataView.kt
> DROID-2012 Sets or Collection | Fix | Provide relation format for sorting search results

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2566 Protocol | Integrate 0.34.0-rc9

- localization/src/main/res/values/strings.xml
> DROID-2531 Settings | What's new url

- payments/build.gradle
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/MembershipPurchase.kt
- payments/src/main/java/com/anytypeio/anytype/payments/playbilling/BillingClientLifecycle.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipViewModel.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActiveWithDifferentSubIdTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierBuilderFallbackOnExplorerTest.kt
> DROID-2575 Membership | Billing purchases logic

- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
> DROID-2577 Object | Fix | Empty args

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
> DROID-2577 Sets | Fix | Template with cover gradient

- app/gradle.properties
> DROID-2334 App | Tech | Bump app version (0.31.0)

- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/playbilling/BillingClientLifecycle.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidBillingUnavailableTest.kt
> DROID-2277 Membership | Apk builds

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2579 Protocol | Integrate 0.34.0

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
> DROID-2427 Membership | Analytics

- .gitignore
- app/src/debug/res/drawable/ic_launcher_background.xml
- app/src/debug/res/drawable/ic_launcher_foreground.xml
> DROID-2581 Design | Debug icon

- gradle/libs.versions.toml
- protocol/src/main/proto/events.proto
> DROID-2582 Protocol | Integrate 0.34.1

- analytics/src/main/java/com/anytypeio/anytype/analytics/features/WidgetAnalytics.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Block.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/Widget.kt
- protocol/src/main/proto/models.proto
> DROID-2584 Protocol | Integrate 0.34.2

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ResExtension.kt
- localization/src/main/res/values/strings.xml
> DROID-2012 Relations | Tag sort

- gradle/libs.versions.toml
> DROID-2592 Protocol | Version 0.34.3

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/objects/ObjectActionAdapter.kt
- core-ui/src/main/res/drawable/ic_object_action_download.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/common/Delegator.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/FileUrlExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectAction.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectSetMenuViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorErrorMessageTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/ParseWidgetTest.kt
> DROID-2596 File as Object | Fix | Can't download files on mobile

- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/OnboardingDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/login/OnboardingMnemonicLoginDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signin/OnboardingRecoveryPhraseLoginScreen.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- domain/src/main/java/com/anytypeio/anytype/domain/debugging/DebugGoroutines.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/login/OnboardingMnemonicLoginViewModel.kt
> DROID-2593 Auth | Tech | Debug goroutines stack

- core-models/src/main/java/com/anytypeio/anytype/core_models/Block.kt
> DROID-2610 Editor | Enhancement | Create link-to-object block with card preview by default

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
> DROID-2545 Global search | Fix | Center crop profile image

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/multiplayer/ShareSpaceInject.kt
- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- domain/src/main/java/com/anytypeio/anytype/domain/object/SpaceViewExt.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/MembershipIncentivesExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-2378 Membership |  Introduce incentives on share-space screen, part 2

- app/src/main/java/com/anytypeio/anytype/di/feature/settings/SpacesStorageDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/SpacesStorageFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModelFactory.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/SpaceStorageScreen.kt
> DROID-2378 Membership | Introduce incentives on remote-storage screen

- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SpaceSettingsDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/space/SpaceSettingsFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/SpaceViewSubscriptionContainer.kt
- domain/src/test/java/com/anytypeio/anytype/domain/multiplayer/SpaceViewSubscriptionContainerTest.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/Settings.kt
> DROID-2378 Membership | Introduce incentives on space-settings screen 

- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetRenderMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/GalleryViewMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2171 Set | Fix | Сorrect display of images in the gallery

- persistence/src/main/java/com/anytypeio/anytype/persistence/networkmode/NetworkModeProvider.kt
> DROID-2615 Login | Tech | Reset the multiplex flag for all users

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/GalleryViewMapper.kt
> DROID-2171 Set | Fix | Gallery image preview size

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/ListWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/TreeWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/TreeWidgetContainerTest.kt
> DROID-2619 Widgets | Enhancement | Improve widget performance

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/ListWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/TreeWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/TreeWidgetContainerTest.kt
> DROID-2619 Widgets | Enhancement | Improve widget performance (#1334)

- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
> DROID-2619 Widgets | Tech | Widget cache proposal

- analytics/build.gradle
- app/build.gradle
- build.gradle
- core-utils/build.gradle
- gradle.properties
- gradle/libs.versions.toml
- localization/build.gradle
- middleware/build.gradle
- persistence/build.gradle
- presentation/build.gradle
- sample/build.gradle
> DROID-2629 App | Tech | Migrate project to Kotlin Symbol Processing (KSP)

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
> DROID-2622 Protocol | Integrate 0.35.0-rc2

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- app/src/main/java/com/anytypeio/anytype/ui/sharing/Sharing.kt
- app/src/main/java/com/anytypeio/anytype/ui/sharing/SharingFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/download/ProcessCancel.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sharing/AddToAnytypeViewModel.kt
> DROID-2642 Sharing extension | Support Videos and Files

- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/Settings.kt
> DROID-2388 Space | Show Personalisation item for every space users

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetCreateBookmarkRecordViewModel.kt
> DROID-2439 Sets | Fix | Bookmark prefill

- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetSettingsViewModel.kt
> DROID-2640 Data View | Fix | Fix view's relations logic

- localization/src/main/res/values/strings.xml
> DROID-2621 Membership | Fix | Text status update

- data/src/main/java/com/anytypeio/anytype/data/auth/repo/AuthCache.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/AuthDataStore.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/CheckAuthorizationStatus.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/GetMnemonic.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/LaunchWallet.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/ResumeAccount.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/repo/AuthRepository.kt
- domain/src/test/java/com/anytypeio/anytype/domain/auth/CheckAuthorizationStatusTest.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultAuthCache.kt
> DROID-2660 Login | Tech | Seed phrase check 

- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/MembershipModels.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActivePurchasedOniOSTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActivePurchasedOniOS.kt
> DROID-2621 Membership | Users notice text

- gradle/libs.versions.toml
> DROID-2661 Protocol | Integrate 0.35.0-rc6

- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/models/MembershipModels.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
> DROID-2595 Membership | Fix | Active tier state

- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
> DROID-2666 Relations | Fix | Do not allow opening object type as object relation

- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationDateValueFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/misc/DateProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationDateValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImpl.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImplTest.kt
> DROID-2501 Relations | Date value problem with GMT -01:00 etc.

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/search/GlobalSearchComponent.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/GlobalSearchViewModel.kt
> DROID-2534 Analytics | Object search screen

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
> DROID-2677 Multiplayer | Share screen, dismiss with scroll

- app/src/main/java/com/anytypeio/anytype/ui/search/GlobalSearchScreen.kt
> DROID-2670 Search | Fix | Related objects menu

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/table/EditorTableMoveRowsColumnsTest.kt
> DROID-2679 Editor | Fix | Fix permission switch behavior

- app/src/main/AndroidManifest.xml
https://github.com/tink-crypto/tink/issues/535#issuecomment-912127671
> DROID-2659 App | Tech | Disable autobackup

- app/src/main/java/com/anytypeio/anytype/ui/sharing/SharingFragment.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImpl.kt
> DROID-2550 Sharing | Fix | Removed sharing object wrapper text

- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/history/Version.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/history/DiffVersions.kt
- domain/src/main/java/com/anytypeio/anytype/domain/history/GetVersions.kt
- domain/src/main/java/com/anytypeio/anytype/domain/history/SetVersion.kt
- domain/src/main/java/com/anytypeio/anytype/domain/history/ShowVersion.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-2688 Version history | Api

- gradle/libs.versions.toml
> DROID-2706 Protocol | Integrate 0.35.0-rc11 MW

- app/src/main/java/com/anytypeio/anytype/di/feature/history/VersionHistoryDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/history/VersionHistoryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/search/GlobalSearchScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/history/VersionHistoryMainScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryVMFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2663 Version history | Versions list screen

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/history/VersionHistoryDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/MainComponent.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/history/VersionHistoryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/search/GlobalSearchScreen.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/history/Version.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/primitives/Primitives.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/history/VersionHistoryMainScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
- domain/src/main/java/com/anytypeio/anytype/domain/history/GetVersions.kt
- domain/src/main/java/com/anytypeio/anytype/domain/misc/DateProvider.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryVMFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImpl.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/history/StubVersionModels.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModelTest.kt
- test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/Object.kt
> DROID-2663 Version history | Ui + logic, part 1 

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetRenderMapper.kt
> DROID-2707 Icons | Title icon size

- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/state/ObjectState.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/DefaultBlockViewRendererTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/table/EditorTableBlockTest.kt
> DROID-2711 Relations | Removing from object

- app/src/main/java/com/anytypeio/anytype/di/feature/home/HomescreenDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- domain/src/test/java/com/anytypeio/anytype/domain/subscriptions/StorelessSubscriptionContainerTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetExtension.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
> DROID-2603 Widgets | Enhancement | Allow creating data view objects via widgets 

- app/build.gradle
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- gradle/libs.versions.toml
> DROID-2709 Tech | Glide, compose

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/Icons.kt
> DROID-2611 Widgets | Fix | Icons

- crowdin.yml
> l10n | Enhancement | Enable be-BY translation

- app/src/androidTest/java/com/anytypeio/anytype/features/editor/base/EditorTestSetup.kt
- app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/EditorDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/ClearLastOpenedObject.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModelFactory.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorPresentationTestSetup.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
> DROID-2521 Navigation | Fix | Fix issue with the last opened object not being cleared correctly

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/Icons.kt
- core-ui/src/main/res/values-night/colors.xml
- core-ui/src/main/res/values/colors.xml
> DROID-2611 Widgets | Design | Design review fixes

- app/src/main/java/com/anytypeio/anytype/di/feature/MainEntryDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/SplashDi.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/auth/DeletedAccountDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/login/OnboardingMnemonicLoginDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/signup/OnboardingSoulCreationDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/settings/LogoutWarningDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/SubscriptionsModule.kt
- domain/src/main/java/com/anytypeio/anytype/domain/subscriptions/GlobalSubscriptionManager.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/auth/account/DeletedAccountViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/login/OnboardingMnemonicLoginViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingSetProfileNameViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModelFactory.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/auth/DeleteAccountViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/splash/SplashViewModelTest.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/LogoutWarningViewModel.kt
> DROID-2718 App | Tech | Introduce wrapper class for global subscriptions

- app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt
- app/src/main/java/com/anytypeio/anytype/di/main/UtilModule.kt
- app/src/main/java/com/anytypeio/anytype/ui/history/VersionHistoryFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/history/VersionHistoryMainScreen.kt
- core-ui/src/main/res/layout/version_history_screen.xml
- domain/src/main/java/com/anytypeio/anytype/domain/misc/DateProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImpl.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/widgets/collection/DateProviderImplTest.kt
> DROID-2663 Version history | Grouping + ui fixes

- app/src/main/java/com/anytypeio/anytype/ui/editor/sheets/ObjectMenuBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/history/VersionHistoryFragment.kt
- app/src/main/res/navigation/graph.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/history/VersionHistoryPreviewScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/ObjectValueCompose.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationExtensions.kt
> DROID-2726 Version history |  Show relation values

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- domain/src/test/java/com/anytypeio/anytype/domain/subscriptions/StorelessSubscriptionContainerTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModel.kt
> DROID-2736 Version History | Analytics

- domain/src/test/java/com/anytypeio/anytype/domain/subscriptions/StorelessSubscriptionContainerTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2720 Global search | The ability to find files in search

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/RequestJoinSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeChangeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SelectObjectTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/OnboardingStartViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/login/OnboardingMnemonicLoginViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingSetProfileNameViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/add/AddOptionsRelationDVViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/add/AddOptionsRelationViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/providers/DataViewObjectRelationProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/providers/DefaultObjectRelationProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/providers/ObjectRelationProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/GlobalSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationTextValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationValueBaseViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/relations/providers/FakeObjectRelationProvider.kt
> DROID-2219 App | Tech|  Release 6 stabilisation

- app/src/main/java/com/anytypeio/anytype/ui/search/GlobalSearchScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/GlobalSearchViewModel.kt
> DROID-2650 Global search | Highlight the title in search results

- gradle/libs.versions.toml
> DROID-2749 Protocol | Integrate 0.35.3 

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
> DROID-2757 Relations | Can't open attachments as files

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/anytypeio/anytype/other/Deeplinks.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- app/src/main/java/com/anytypeio/anytype/ui/payments/MembershipFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/misc/DeepLinkResolver.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
> DROID-2722 Membership | Open tier deeplink

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/history/VersionHistoryMainScreen.kt
> DROID-2743 Version history | Design review

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingMnemonicPhraseScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingSetProfileNameViewModel.kt
> DROID-2758 Analytics | Fix | Fix onboarding analytics

- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
> DROID-2302 Multiplayer | Fix | Show leave space screen for editors

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/types/create/CreateObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/types/edit/TypeEditFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/Markup.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/filter/FilterViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sharing/AddToAnytypeViewModel.kt
> DROID-2219 Sentry | Release 6

- app/build.gradle
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/MiddlewareProtobufLogger.kt
> DROID-2781 Tech | Measure command execution time

- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModelTest.kt
> DROID-2781 Tech | Measure command execution time, 2

- gradle/libs.versions.toml
> DROID-2783 Protocol | Integrate 0.36.0-rc3

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/splash/SplashFragment.kt
- app/src/main/res/navigation/graph.xml
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsCache.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsDataRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/GetLastOpenedObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/config/UserSettingsRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/spaces/ClearLastOpenedSpace.kt
- domain/src/main/java/com/anytypeio/anytype/domain/spaces/GetLastOpenedSpace.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultUserSettingsCache.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModelFactory.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/splash/SplashViewModelTest.kt
> DROID-2731 Vault | Enhancement | Restoring either last opened space or vault

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/syncstatus/SpaceSyncStatusScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/StatusBadgeWidget.kt
- core-ui/src/main/res/drawable/ic_arrow_top_end.xml
- core-ui/src/main/res/drawable/ic_sync_limitations.xml
- core-ui/src/main/res/drawable/ic_sync_slow_10.xml
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/FragmentExtensions.kt
- core-utils/src/main/res/values/strings.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetCommand.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2780 Sync status | Need update status

- gradle/libs.versions.toml
- protocol/src/main/proto/events.proto
> DROID-2791 Protocol | Integrate 0.35.6

- core-models/src/main/java/com/anytypeio/anytype/core_models/SyncStatus.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ResExtension.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/StatusBadgeWidget.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/ThreadStatusMiddlewareChannel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sync/SyncStatusView.kt
> DROID-2785 Sync status | Need update status

- localization/src/main/res/values/strings.xml
> DROID-2785 Sync status | Need update status, text

- app/src/main/java/com/anytypeio/anytype/di/main/SubscriptionsModule.kt
- app/src/main/java/com/anytypeio/anytype/other/BasicLogger.kt
- domain/src/main/java/com/anytypeio/anytype/domain/debugging/Logger.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/ActiveSpaceMemberSubscriptionContainer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/DefaultUserPermissionProvider.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/SpaceViewSubscriptionContainer.kt
- domain/src/test/java/com/anytypeio/anytype/domain/subscriptions/StorelessSubscriptionContainerTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModel.kt
> DROID-2825 Tech | Catch subscription errors

- domain/src/main/java/com/anytypeio/anytype/domain/spaces/SpaceDeletedStatusWatcher.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/FilesStorageViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SelectSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
> DROID-2825 Tech | Catch subscription errors, 2

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerLayoutCoverWidget.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerLayoutWidget.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/WidgetHeader.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/GalleryViewMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ViewerLayoutWidgetUi.kt
> DROID-2699 Set | Fix | Gallery view, support cover attachments

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/relations/RelationBlockViewHolder.kt
> DROID-2817 Relations | Fix | Convert file sizes in Relation block to KB/MB

- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/DocumentExternalEventReducer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-2826 Editor | Fix | Cursor jumps back inside bullet list

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorBackspaceDeleteTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorFocusTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetActionsTest.kt
> DROID-2826 Editor | Tech | Remove legacy LiveData

- app/src/main/java/com/anytypeio/anytype/di/main/ConfigModule.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/config/GatewayProvider.kt
> DROID-2731 Vault | Tech | Fix gateway provider

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectType.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/multiplayer/Multiplayer.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/syncstatus/SpaceSyncStatusScreen.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-2834 Protocol | Integrate 0.36.0-rc4

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
> DROID-2833 Tech | Refactoring after compose update

- gradle/libs.versions.toml
> DROID-2686 App | Tech | Update libs

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/syncstatus/SpaceSyncStatusScreen.kt
- localization/src/main/res/values/strings.xml
- middleware/build.gradle
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/SyncAndP2PChannelContainer.kt
- middleware/src/test/java/com/anytypeio/anytype/middleware/interactor/EventHandlerChannelImplTest.kt
- middleware/src/test/java/com/anytypeio/anytype/middleware/interactor/SyncAndP2PStatusEventsStoreImplTest.kt
> DROID-2838 Sync status | P2P status, design update

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/syncstatus/SpaceSyncStatusScreen.kt
> DROID-2838 Sync status | P2P status, need update error state

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-2431 Sync status | Exclude space members for sync status

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/syncstatus/SpaceSyncStatusScreen.kt
> DROID-2780 Sync status | Fix | Icon update

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-2875 Protocol | Integrate 0.36.0-rc6

- app/src/main/java/com/anytypeio/anytype/di/feature/AllContentDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModelFactory.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentMenu.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
> DROID-2886 All content | Enhancement | Paging

- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/types/create/TypeCreationScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/types/edit/TypeEditScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/types/views/TypeEditWidget.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectTypeIds.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentMenu.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/navigation/AppNavigation.kt
> DROID-2856 All content |  Object types, part 1

- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
> DROID-2897 All Content | Search, subscription fixes

- app/src/main/java/com/anytypeio/anytype/di/feature/AllContentDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionScreen.kt
- app/src/main/res/navigation/graph.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/components/BottomNavigationMenu.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModelFactory.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
> DROID-2885 All content | Navigation widget

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
> DROID-2866 All content | Analytics

- app/src/main/java/com/anytypeio/anytype/di/feature/AllContentDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/DismissBackground.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModelFactory.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
> DROID-2885 All Content | Swipe to dismiss

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SetsExtension.kt
> DROID-2772 Relations | Fix | Removed duplicate format in File attachment relation

- app/src/main/java/com/anytypeio/anytype/di/feature/AllContentDI.kt
- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationEditScreen.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectTypeIds.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModelFactory.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentMenu.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/navigation/AppNavigation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2856 All content | Types & relations tabs

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectType.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SupportedLayouts.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-2910 Protocol | Enhancement | MW 0.36.0-rc7

- app/src/main/java/com/anytypeio/anytype/di/feature/AllContentDI.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/DismissBackground.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModelFactory.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
> DROID-2911 All Content | User permissions

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- app/src/main/res/layout/fragment_object_set.xml
- app/src/main/res/xml/fragment_object_set_scene.xml
> DROID-2731 Sets | Fix | Fix layout issues

- app/src/main/java/com/anytypeio/anytype/di/main/WorkspaceModule.kt
- domain/src/main/java/com/anytypeio/anytype/domain/workspace/WorkspaceManager.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/tagstatus/TagOrStatusValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/GlobalSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/subscription/DataViewSubscription.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/Subscription.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateSetViewTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetConvertToCollectionTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt
> DROID-2882 App | Tech | Remove cross-space subscriptions

- app/src/main/java/com/anytypeio/anytype/ui/types/edit/TypeEditFragment.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/types/TypeEditViewModel.kt
> DROID-2911 All content | Fixes, part 2

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
> DROID-2849 All Content | Fix | Make the widget non-clickable in edit mode.

- core-models/src/main/java/com/anytypeio/anytype/core_models/ThemeColor.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/util/SystemColorTest.kt
> DROID-2657 App | Tech | Release 7 Stabilisation

- localization/src/main/res/values/strings.xml
> DROID-2912 All Content | Rename title

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/CreateOrEditOptionScreen.kt
> DROID-2923 Relations | Fix | Create option ui

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/settings/SpacesStorageDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SpaceSettingsDI.kt
- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/base/NavigationRouter.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/RemoteFilesManageFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/SpacesStorageFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/space/SpaceSettingsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionScreen.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/navigation/AppNavigation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/SpacesStorageViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionUiState.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/ObjectView.kt
> DROID-2924 All Content | Bin, empty state + viewer permissions

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
> DROID-2925 All Content | Fix | Sorts order

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/MultiSelectTopToolbarWidget.kt
- core-ui/src/main/res/layout/widget_multi_select_top_toolbar.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/ControlPanelMachine.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/control/ControlPanelState.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/ControlPanelStateReducerTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorMultiSelectModeTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorQuickStartingScrollAndMoveTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorScrollAndMoveTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/styling/EditorStyleBackgroundToolbarTest.kt
Clicking it selects all blocks, and if all blocks are already selected, nothing happens on subsequent clicks
---
---
> DROID-2631 Editor | Feature | Add a "Select All" button;

- app/src/main/java/com/anytypeio/anytype/ui/splash/PulsatingCircleScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/splash/PulsatingCirclesScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/splash/SplashFragment.kt
- app/src/main/res/layout/fragment_splash.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
> DROID-2829 Splash Screen | Enhancement | Updated splash screen and added animation on app launch

- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-2914 All Content | Create types and relations

- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsCache.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsDataRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/all_content/RestoreAllContentState.kt
- domain/src/main/java/com/anytypeio/anytype/domain/config/UserSettingsRepository.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultUserSettingsCache.kt
> DROID-2928 All Content | Fix | Sort order

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-2929 All Content | Unlinked items, description

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperExtensions.kt
> DROID-2926 All Content | Show snippet

- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-2885 All content | Undo delete object by swipe

- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/components/BottomNavigationMenu.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
> DROID-2943 All content | Viewer only permission

- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/CreateSpaceScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/Spaces.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/LaunchAccount.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/ResumeAccount.kt
- domain/src/main/java/com/anytypeio/anytype/domain/spaces/SpaceDeletedStatusWatcher.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/CreateSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SelectSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileSettingsViewModel.kt
> DROID-2657 App | Tech | Regress testing fixes for release 7

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ComposableExtensions.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/MiddlewareProtobufLogger.kt
> DROID-2885 All content | LazyList refactoring

- app/src/main/java/com/anytypeio/anytype/ui/vault/IntroduceVaultScreen.kt
> DROID-2935 Vault | Image preview size fix

- core-ui/build.gradle
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/dataview/ViewerGridAdapter.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/media/Bookmark.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/media/Picture.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/GridCellObjectItem.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconWidget.kt
- core-ui/src/main/res/drawable/ic_icon_loading.xml
- core-ui/src/test/java/com/anytypeio/anytype/core_ui/features/dataview/GridDiffUtilTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetRenderMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/GalleryViewMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ListViewMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SetsExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/model/Viewer.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/TagAndStatusTests.kt
> DROID-2950 Icons | Objets icons in sets and widgets

- domain/src/main/java/com/anytypeio/anytype/domain/bin/EmptyBin.kt
- domain/src/main/java/com/anytypeio/anytype/domain/launch/GetDefaultObjectType.kt
- domain/src/main/java/com/anytypeio/anytype/domain/page/CreateObjectByTypeAndTemplate.kt
- domain/src/main/java/com/anytypeio/anytype/domain/templates/GetTemplates.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/LimitObjectTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2883 App | Tech | IsHiddenDiscovery filter added

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionScreen.kt
- app/src/main/res/layout/fragment_editor.xml
- app/src/main/res/layout/fragment_object_set.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/components/BottomNavigationMenu.kt
- core-ui/src/main/res/layout/widget_main_bottom_toolbar.xml
- core-ui/src/main/res/values/dimens.xml
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-2941 Navigation | Enhancement | Main navigation toolbar, design + read only state

- app/src/main/java/com/anytypeio/anytype/ui/search/GlobalSearchScreen.kt
> DROID-2657 Global search | Fix | Search bar background

- localization/src/main/res/values/strings.xml
> DROID-2957 Membership |  Anytype Identity the same for all locales  

- app/src/main/res/layout/fragment_editor.xml
- app/src/main/res/layout/fragment_object_set.xml
- core-ui/src/main/res/drawable/widget_main_bottom_toolbar_background.xml
> DROID-2960 Design | Navigation menu design

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2872 Create object | Filter by templates object type

- localization/src/main/res/values/strings.xml
- payments/src/main/java/com/anytypeio/anytype/payments/screens/AnyNameView.kt
> DROID-2957 Membership | Any name localization fix

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeChangeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2872 Set | Create set by templates

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- domain/src/main/java/com/anytypeio/anytype/domain/object/SpaceViewExt.kt
- domain/src/test/java/com/anytypeio/anytype/domain/object/SpaceViewExtKtTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
> DROID-2984 Membership | Fix | New space members limit

- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/LimitObjectTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-2986 Chats | Fix | Hide chats in relations and filters

- gradle/libs.versions.toml
> DROID-2997 Protocol | Integrate 0.36.3

- gradle/libs.versions.toml
> DROID-3000 Protocol | Integrate 0.36.4 

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectTypeIds.kt
- domain/src/main/java/com/anytypeio/anytype/domain/launch/GetDefaultObjectType.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/SelectObjectTypeViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionCreateAndAddObjectTest.kt
> DROID-3002 App | Page as default type

- core-ui/src/main/res/drawable/ic_membership.xml
> DROID-2939 Membership | Fix | Update icon

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentMenu.kt
> DROID-2932 All content | Design | Menu backround

- app/src/main/java/com/anytypeio/anytype/di/feature/CreateObjectDI.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/CreateObjectViewModel.kt
> DROID-2989 Create object | Fix | Object creation via the application icon

- app/src/main/java/com/anytypeio/anytype/ui/editor/CreateObjectFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorModalFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/templates/EditorTemplateFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/templates/TemplateSelectAdapter.kt
- domain/src/main/java/com/anytypeio/anytype/domain/templates/CreateTemplate.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2998 Set | Fix | The query does not change in the set in some cases

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/GalleryViewMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ListViewMapper.kt
> DROID-2987 App | Tech | Fix crashes from Sentry

- app/src/main/java/com/anytypeio/anytype/di/feature/objects/SelectObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/SelectObjectTypeBaseFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/creation/SelectObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/types/pickers/AppDefaultObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/types/pickers/ObjectSelectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/types/pickers/ObjectTypeSelectionListener.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/types/pickers/OnObjectSelectTypeAction.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/PersonalizationSettingsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionFragment.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/FragmentExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
> DROID-3006 Create object | Fix | Crash on type selection

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- presentation/src/test/java/com/anytypeio/anytype/presentation/types/ObjectTypeChangeViewModelTest.kt
> DROID- 3010 Tech | AGP and Kotlin updated

- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2987 Sentry | Fix crash in collection screen

- gradle/libs.versions.toml
> DROID-3011 Protocol | Integrate 0.36.6

- gradle/libs.versions.toml
> DROID-3012 Protocol | MW 0.36.4

- gradle/libs.versions.toml
> DROID-3012 Protocol | Integrate 0.36.5

- gradle/libs.versions.toml
> DROID-3015 Protocol | Integrate 0.36.7

- core-ui/src/main/res/values-night/colors.xml
- core-ui/src/main/res/values/colors.xml
> DROID-2909 Design |  Update colors to match Figma variables (Iteration 1)

- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/dataview/interactor/SetActiveViewer.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
> DROID-2578 Tech | Implement BlockDataViewSetActiveView 

- app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt
- app/src/main/java/com/anytypeio/anytype/ui/templates/TemplateFragment.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/object/GetObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/object/OpenObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/objects/ObjectWatcher.kt
- domain/src/main/java/com/anytypeio/anytype/domain/page/AddBackLinkToObject.kt
- domain/src/main/java/com/anytypeio/anytype/domain/page/CloseBlock.kt
- domain/src/main/java/com/anytypeio/anytype/domain/page/OpenPage.kt
- domain/src/main/java/com/anytypeio/anytype/domain/sets/OpenObjectSet.kt
- domain/src/main/java/com/anytypeio/anytype/domain/templates/OpenTemplate.kt
- domain/src/main/java/com/anytypeio/anytype/domain/workspace/WorkspaceManager.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/TemplateViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectCreateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorBackButtonTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorTextUpdateTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetNavigationTest.kt
> DROID-3001 App | Tech | Refactoring - provide space

- core-models/src/main/java/com/anytypeio/anytype/core_models/Config.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectType.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/auth/AuthMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
- test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/Auth.kt
> DROID-3032 Protocol | Integrate 0.37.0-alpha01

- gradle/libs.versions.toml
- protocol/src/main/proto/changes.proto
> DROID-3033 Protocol | Integrate 0.36.8

- gradle/libs.versions.toml
- protocol/src/main/proto/changes.proto
> DROID-3035 Protocol | Integrate 0.37.0-alpha02

- gradle/libs.versions.toml
> DROID-3041 Protocol | Integrate MW 0.36.9

- gradle/libs.versions.toml
> DROID-3051 Protocol | Integrate 0.36.10

- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/base/NavigationRouter.kt
- app/src/main/java/com/anytypeio/anytype/ui/date/DateObjectFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/library/LibraryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/RemoteFilesManageFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionFragment.kt
- app/src/main/res/navigation/graph.xml
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/models/DateObjectModels.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/presentation/DateObjectViewModel.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/DateObjectListsScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/DateObjectScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/DateObjectSheetScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/DateObjectTopToolbar.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/navigation/AppNavigation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2795 Date as an object | Ui + navigation

- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/login/OnboardingMnemonicLoginDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/SubscriptionsModule.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signin/OnboardingRecoveryPhraseLoginScreen.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/debugging/DebugAccountSelectTrace.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/login/OnboardingMnemonicLoginViewModel.kt
> DROID-2773 Tech | Debug, implement account select trace

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
> DROID-3061 Date picker | Fix | Update year range

- app/src/main/res/values/colors.xml
> DROID-2909 Added "gradient_white" to colors

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/history/VersionHistoryMainScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/AvatarIconView.kt
- core-ui/src/main/res/drawable/default_ripple.xml
- core-ui/src/main/res/drawable/ic_membership.xml
- core-ui/src/main/res/drawable/ic_nav_panel_back.xml
- core-ui/src/main/res/drawable/ic_nav_panel_plus.xml
- core-ui/src/main/res/drawable/ic_nav_panel_search.xml
- core-ui/src/main/res/drawable/widget_main_bottom_toolbar_background.xml
- core-ui/src/main/res/values-night/colors.xml
- core-ui/src/main/res/values/colors.xml
…lor;
Updated stroke background color in VersionHistoryMainScreen; Added missing colors to the project;
---
---
> DROID-2909 | Design | Changed background in navigation panel and updated icon colors

- app/src/main/assets/syntax/languages.json
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/other/Code.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/text/CodeTextInputWidget.kt
- core-ui/src/main/res/layout/item_block_code_snippet.xml
- library-syntax-highlighter/src/main/java/com/anytypeio/anytype/library_syntax_highlighter/Syntaxes.kt
- library-syntax-highlighter/src/main/java/com/anytypeio/anytype/library_syntax_highlighter/SyntaxtHighlighterExt.kt
- localization/src/main/res/values-be-rBY/strings.xml
- localization/src/main/res/values-de-rDE/strings.xml
- localization/src/main/res/values-es-rES/strings.xml
- localization/src/main/res/values-fr-rFR/strings.xml
- localization/src/main/res/values-in-rID/strings.xml
- localization/src/main/res/values-it-rIT/strings.xml
- localization/src/main/res/values-nl-rNL/strings.xml
- localization/src/main/res/values-no-rNO/strings.xml
- localization/src/main/res/values-pt-rBR/strings.xml
- localization/src/main/res/values-ru-rRU/strings.xml
- localization/src/main/res/values-tr-rTR/strings.xml
- localization/src/main/res/values-uk-rUA/strings.xml
- localization/src/main/res/values-zh-rCN/strings.xml
- localization/src/main/res/values-zh-rTW/strings.xml
- localization/src/main/res/values/strings.xml
…e for code snippets.
- Ensured text color matches desktop implementation
---
---
>  DROID-3003 Editor | Enhancement | Add 'Plain Text' option and align text color with desktop

- ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/fstorage/FilesStorageScreen.kt
> DROID-3065 Local storage | Design | Modified Spacer size in LocalStorageScreen

- core-ui/src/main/res/drawable/ic_nav_panel_back.xml
- core-ui/src/main/res/drawable/ic_nav_panel_plus.xml
- core-ui/src/main/res/drawable/ic_nav_panel_search.xml
- core-ui/src/main/res/drawable/widget_main_bottom_toolbar_background.xml
> DROID-3083 Design | Fix | Revert navigation panel colors to the previous values

- localization/src/main/res/values-ru-rRU/strings.xml
> DROID-3089 Multiplayer | Fix | Update russian localization

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
> DROID-3085 All Objects | Fix | Untitled objects, swipe

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenToolbar.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionScreen.kt
> DROID-3044 Chats | Fix | Layouting fixes

- gradle/libs.versions.toml
> DROID-3093 Protocol | Integrate MW 0.37.3

- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-3098 Chats | Enhancement | Added dropdown menu for chatbox attachments

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/GalleryViewMapper.kt
> DROID-3099 Set | Fix | Image objects not displaying covers in gallery view

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/ObjectRelationListFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
https://sentry.anytype.io/organizations/anytype/issues/58701/?project=5&referrer=release-issue-stream
https://sentry.anytype.io/organizations/anytype/issues/22848/?project=5&referrer=release-issue-stream
https://sentry.anytype.io/organizations/anytype/issues/57116/?project=5&referrer=release-issue-stream
> DROID-3063 App | Tech | Release stabilisation

- device/src/main/java/com/anytypeio/anytype/device/providers/AppDefaultDateFormatProvider.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/FieldsScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/FieldsSheetScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/MainScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/models/DateEvent.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateModels.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateViewModel.kt
> DROID-2795 Date as an object | Search by fields + scroll to

- app/gradle.properties
- app/src/main/java/com/anytypeio/anytype/other/MediaPermissionHelper.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/DragAndDropDelegate.kt
- app/src/main/res/layout/fragment_object_type_change.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/MiddlewareProtobufLogger.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/ext/BlockViewExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/styling/StyleToolbarExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/SetsExtension.kt
> DROID-3110 Release 7.1 | Sentry issues

- app/src/androidTest/java/com/anytypeio/anytype/features/editor/base/EditorTestSetup.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/EditorDI.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/EditorDatePicker.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/slash/holders/ActionMenuHolder.kt
- core-ui/src/main/res/layout/item_slash_widget_object_type.xml
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/const/SlashConst.kt
- domain/src/main/java/com/anytypeio/anytype/domain/page/CreateBlockLinkWithObject.kt
- domain/src/test/java/com/anytypeio/anytype/domain/page/CreateBlockLinkWithObjectTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/slash/SlashExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/slash/SlashItem.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/model/EditorDatePicker.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetClicksTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetFilterTest.kt
> DROID-2794 Date as an object | Slash menu, select date

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/chats/Chat.kt
- domain/src/main/java/com/anytypeio/anytype/domain/media/UploadFile.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionView.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionViewModel.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionViewModelFactory.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionPreviews.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionScreen.kt
- feature-discussions/src/main/res/drawable/ic_clear_chatbox_attachment.xml
> DROID-3044 Chats | Enhancement | Naive implementation for media attachments 

- app/src/main/java/com/anytypeio/anytype/di/feature/DateObjectDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/date/DateObjectFragment.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/mapping/DateObjectModelsExt.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/MainScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/ObjectsScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/models/DateEvent.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateModels.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectCommand.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectVMFactory.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
> DROID-2795 Date as an object | Move to bin by right-to-left swipe

- domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperMapper.kt
> DROID-2794 Editor | Fix | Mention object type name

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- analytics/src/main/java/com/anytypeio/anytype/analytics/props/Props.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Intent.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Orchestrator.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
> DROID-3114 Analytics | Date as an Object

- gradle/libs.versions.toml
> DROID-3135 Protocol | Integrate 0.38.2

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/ListWidget.kt
> DROID-2794 Widgets | Fix | Untitled objects 

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/ObjectRelationListFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/relations/RelationDateValueFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/ComposePreview.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/EditorDatePicker.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/relations/DatePickerContent.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/CalendarScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/RelationDateValueViewModel.kt
> DROID-3108 Date as an Object | Add the “Open selected date” option to the Date Picker.

- core-models/src/main/java/com/anytypeio/anytype/core_models/SupportedLayouts.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetConfig.kt
> DROID-2797 Date as an Object | Tree widget, relative dates

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3160 Protocol | Integrate 0.38.3

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/CollectionViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/collection/Subscription.kt
> DROID-3120 Files | Show hidden files in Manage space files screen

- localization/src/main/res/values/strings.xml
> DROID-3169 Date as an Object | Rename "Mentioned in" to "Mentions"

- gradle/libs.versions.toml
> DROID-3180 Protocol | Integrate 0.38.6

- gradle/libs.versions.toml
> DROID-3186 Protocol Integrate 0.38.7

- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectViewModel.kt
- feature-date/src/test/java/com/anytypeio/anytype/feature_date/DateObjectViewModelTest.kt
> DROID-2793 Date as an Object | Tech | Refactoring main state change

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-2963 Editor | Hide types widget on a back callback

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/media/File.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/model/BlockView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/file_layout/FileLayoutTest.kt
> DROID-2898 File as Object | Layout, part 2

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/file_layout/FileLayoutTest.kt
> DROID-2898 File as Object | File name with extension in the title

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorLockPageTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/file_layout/FileLayoutTest.kt
> DROID-2898 File as an Object | Full-screen preview, shown in a large size.

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/adapter/MentionAdapter.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
> DROID-3212 Editor | Fix | Mention create object item doesn't update

- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
> DROID-2898 File as an Object | Action delete

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/ChatReactionDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/DiscussionFragment.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/DiscussionsDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/MainComponent.kt
- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatReactionFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/res/navigation/graph.xml
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/ChatReactionViewModel.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionViewModel.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionViewModelFactory.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/ChatReactionPicker.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionPreviews.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-3210 Space-level chats | Enhancement | Integrate emoji picker

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/text/MentionSpan.kt
> DROID-2952 Editor | Design | Mention font

- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/ChatReactionDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatReactionFragment.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsCache.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/UserSettingsDataRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/ObserveRecentlyUsedChatReactions.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/SetRecentlyUsedChatReactions.kt
- domain/src/main/java/com/anytypeio/anytype/domain/config/UserSettingsRepository.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/ChatReactionViewModel.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/ChatReactionPicker.kt
- localization/src/main/res/values/strings.xml
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultUserSettingsCache.kt
- persistence/src/main/proto/preferences.proto
> DROID-3210 Space-level chats | Enhancement | Save recently used chat reactions and display it in the dedicated section of the reaction picker

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/mapping/DateObjectModelsExt.kt
> DROID-3215 Date as an object | Fix | Space member is removed by swiping

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/ChatReactionDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/DiscussionFragment.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/discussions/SelectChatReactionDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/MainComponent.kt
- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatReactionFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/chats/SelectChatReactionFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/res/navigation/graph.xml
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/ChatReactionViewModel.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/SelectChatReactionViewModel.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/ChatReactionPicker.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/ChatReactionScreen.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionPreviews.kt
- feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-3217 Space-level chat | Enhancement | Screen with message reaction and corresponding members

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
> DROID-3072 App | Tech | Migrate to Android photo picker

- app/src/main/java/com/anytypeio/anytype/di/feature/PrimitivesObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/lists/objects/ObjectsListScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/lists/objects/ObjectsModel.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/lists/objects/stubs/Stubs.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/mapping/DateObjectModelsExt.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/MainScreen.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/models/DateEvent.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/ui/models/PreviewStubs.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateModels.kt
- feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/TypeEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/TypeMainScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HeaderScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HorizontalButtons.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/TopToolbar.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/objects/ObjectsHeader.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/templates/TemplatesHeader.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/templates/TemplatesList.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeModels.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeSearchParams.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeVmFactory.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/SearchParams.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/Models.kt
> DROID-3013 Primitives | Edit type screen, part 2

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/cover/SelectCoverGalleryFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/modals/IconPickerFragmentBase.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/cover/SelectCoverViewModel.kt
> DROID-3072 Tech | Migrate to Android Photo Picker, part 2

- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/permissions/BlockPermissions.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/permissions/ObjectPermissions.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/objects/ObjectPermissionsTest.kt
- test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/Block.kt
> DROID-2192 Tech | Object permissions

- gradle/libs.versions.toml
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-3250 Protocol | Enhancement | MW 0.39.0-rc4

- gradle/libs.versions.toml
> DROID-3255 Protocol | Integrate 0.39.0-rc5

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
> DROID-3246 FaO | Fix | Limit reached message is disabled

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/profile/ParticipantScreen.kt
- core-ui/src/main/res/drawable/ic_loading_state_112.xml
> DROID-3239 Profile | Fix | Loading state for profile image

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/profile/ParticipantScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/profile/ParticipantEvent.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/profile/ParticipantViewModel.kt
> DROID-3239 Profile | Enhancement | Ui fixes

- core-models/src/main/java/com/anytypeio/anytype/core_models/restrictions/ObjectRestriction.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-3271 Protocol | Integrate 0.39.0-rc07

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/profile/ParticipantScreen.kt
- core-ui/src/main/res/drawable/ic_participant_edit.xml
> DROID-3239 Profile | Enhancement | Ui fixes, part 2

- app/src/main/java/com/anytypeio/anytype/di/feature/vault/VaultDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/profile/ParticipantScreen.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/profile/ProfileIconView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
> DROID-3225 Vault | Enhancement | Replace settings icon by user icon

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModelBase.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectSetMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetCommand.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-3281 Objects | Enhancement | Always show three-dots menu, but apply space member permissions

- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/main/MainSettingScreen.kt
> DROID-3285 Profile | Fix | Update profile icon menu colors

- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/model/Viewer.kt
> DROID-3290 Set | Fix | Removed ‘equal’ condition for selection relations

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetRecordDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/modals/SetObjectSetRecordNameFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Inviting.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/DesignSystemButtons.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerEditWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetRecordViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/model/Viewer.kt
> DROID-3289 Sets | Fix | Object name and View name are updated dynamically

- app/src/main/java/com/anytypeio/anytype/ui/relations/value/ObjectValueFragment.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceListViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/ObjectSetRecordViewModelTest.kt
> DROID-3239 Participant screen | Open from relations values

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/ObjectTopToolbar.kt
- core-ui/src/main/res/drawable/ic_default_top_back.xml
> DROID-3219 App | Design | Minor design fixes

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ViewExtension.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBubble.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
> DROID-3307 Space-level chat | Enhancement | Basic mention in bubbles

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/relations/RelationBlockViewHolder.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/GridCellFileItem.kt
> DROID-3295 Editor | Fix | Proper update of the file relations

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/profile/ParticipantScreen.kt
> DROID-3270 Profile | Design | On dismiss screen

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3319 Protocol | Integrate MW 0.39.1

- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
> DROID-3296 Analytics | Vault, change space

- localization/src/main/res/values-ru-rRU/strings.xml
> DROID-3292 Multiplayer | Fix | Update buttons text

- localization/src/main/res/values-ru-rRU/strings.xml
> DROID-3292 Multiplayer | Fix | Update buttons text, 2 attempt

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBoxAttachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/res/drawable/ic_chat_box_attachment_error_circle.xml
> DROID-3283 Space-level chat | Enhancement | Loading state for chat box attachments + blocking send action while uploading

- app/src/main/java/com/anytypeio/anytype/di/feature/PrimitivesObjectTypeDI.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/primitives/FieldValues.kt
- domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt
- domain/src/main/java/com/anytypeio/anytype/domain/primitives/SetObjectTypeRecommendedFields.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiStateExt.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HeaderScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/templates/TemplatesList.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/SearchParams.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/TypeViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/VmFactory.kt
- localization/src/main/res/values/strings.xml
> DROID-3014 Primitives | Fields screen, part 2

- app/build.gradle
- core-ui/build.gradle
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/HapticExt.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/util/DragAndDropUtils.kt
- feature-object-type/build.gradle
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/EditScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HeaderScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/TypeViewModel.kt
- gradle/libs.versions.toml
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- sample/build.gradle
> DROID-3013 Primitives |  Fields, part 3

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/fragment_object_menu.xml
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ui/BaseBottomSheetComposeFragment.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ui/BaseBottomSheetFragment.kt
> DROID-3300 App | Fix | Expand bottom sheet in landscape mode

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBoxAttachments.kt
> DROID-3098 Space-level | Enhancement | Editing attachments

- app/src/main/java/com/anytypeio/anytype/di/feature/ObjectRelationListDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectFieldsFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/DropDownMenu.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldEmpty.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeCheckbox.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeDate.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeFile.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeMultiselect.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeObjects.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeSelect.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldTypeText.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldsListScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/MultiSelectPreviews.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/relations/DocumentRelationAdapter.kt
- core-ui/src/main/res/drawable/ic_section_local_fields.xml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/menu/ObjectSetMenuViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectRelationListViewModelFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
> DROID-3014 Primitives | Object sidebar, actions

- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiStateExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
> DROID-3390 Primitives | Don't show file fields in the sidebar

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-3411 Protocol | Integrate 0.40.0-rc1 + AGP 8.8.1

- gradle/libs.versions.toml
> DROID-3412 Protocol | Integrate 0.40.0-rc2

- app/src/main/java/com/anytypeio/anytype/di/common/ComponentManager.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/settings/DebugDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/MainComponent.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/DebugFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/DebugScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/ProfileSettingsFragment.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/settings/VaultSettings.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/tools/IO.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileScreen.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileSettingsViewModel.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultUserSettingsCache.kt
- persistence/src/main/proto/preferences.proto
- persistence/src/test/java/com/anytypeio/anytype/persistence/UserSettingsCacheTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/DebugViewModel.kt
> DROID-3407 App | Tech | New debug menu + allow exporting work directory

- app/src/main/java/com/anytypeio/anytype/di/feature/PrimitivesObjectTypeDI.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/primitives/FieldValues.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TemplatesPreview.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- domain/src/main/java/com/anytypeio/anytype/domain/objects/StoreOfRelations.kt
- domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiStateExt.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/VmFactory.kt
- feature-object-type/src/test/java/com/anytypeio/anytype/feature_object_type/TestFieldsMappping.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/DefaultBlockViewRendererTest.kt
> DROID-3419 Primitives | Support type layout in objects

- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectFieldsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- app/src/main/res/navigation/nav_editor_modal.xml
- app/src/main/res/navigation/nav_templates_modal.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/permissions/ObjectPermissions.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TemplatesPreview.kt
- libs/build.gradle
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- versioning.gradle
> DROID-3430 Primitives | Fix | Misc. fixes

- app/src/main/java/com/anytypeio/anytype/di/feature/PrimitivesObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFieldsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/SearchBar.kt
- domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt
- domain/src/main/java/com/anytypeio/anytype/domain/primitives/SetObjectTypeHeaderRecommendedFields.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/AddScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiStateExt.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/VmFactory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
> DROID-3424 Primitives | Add field screen

- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFieldsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/TypeScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/objects/ObjectsHeaderScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/TreeWidgetContainerTest.kt
> DROID-3013 Primitives | Type screen, Sets migration, part 1

- gradle/libs.versions.toml
- protocol/src/main/proto/models.proto
> DROID-3439 Protocol | Integrate 0.40.0-rc5

- app/src/main/java/com/anytypeio/anytype/ui/primitives/WithSetScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/templates/TemplatesModalList.kt
> DROID-3435 Promitives | Type page as Set, part 2

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
> DROID-3456 Protocol | Integrate 0.40.0-rc6

- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/add/ui/AddScreen.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/edit/ui/EditPropertyScreen.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/edit/ui/NewPropertyScreen.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/edit/ui/PropertyScreen.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/edit/ui/ViewPropertyScreen.kt
> DROID-3429 Primitives | Edit type properties, part 3

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-3470 Protocol | Integrate 0.40.0-rc7

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HorizontalButtons.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/EditTypePropertiesViewModel.kt
- localization/src/main/res/values/strings.xml
> DROID-3424 Primitives | Updating the logic of adding a new Property to a Type 

- app/src/main/java/com/anytypeio/anytype/di/feature/spaces/SpaceSettingsDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/objects/types/pickers/AppDefaultObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/PersonalizationSettingsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/space/SpaceSettingsFragment.kt
- app/src/main/res/navigation/graph.xml
- core-ui/src/main/res/drawable/ic_fields_24.xml
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/Extensions.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Items.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/NewSettings.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Previews.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/PersonalizationSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/UiEvent.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/UiState.kt
> DROID-3375 New settings | Enhancement | Default object type and members sections

- app/src/main/java/com/anytypeio/anytype/ui/settings/space/SpaceSettingsFragment.kt
- app/src/main/res/navigation/graph.xml
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Icon.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Items.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/NewSettings.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/UiEvent.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/UiState.kt
> DROID-3375 New settings | Enhancement | Settings as fullscreen fragment + Navigation to remote storage + Delete space UX + other misc. fixes

- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/LeaveSpaceWarning.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/DeleteSpaceWarning.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/DesignSystemButtons.kt
- localization/src/main/res/values/strings.xml
> DROID-3375 New settings | Enhancement | Redesigned delete-space and leave-space warnings

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/TypeIconView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectIcon.kt
> DROID-3367 Primitives | Type icons

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/animations/LoadingIcon.kt
> DROID-3367 Primitives | Loading icon

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/models.proto
> DROID-3493 Protocol | Integrate 0.40.0

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
> DROID-3013 Set | Update title logic

- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectFieldsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFieldsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- app/src/main/res/layout/fragment_object_menu.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldsListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/InfoScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
> DROID-3505 Primitives | Properties screens, ui updates

- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/ObjectIconMapper.kt
> DROID-3367 Primitives | Type icon, pre-primitives types

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-3513 Protocol | Enhancement | MW 0.40.3

- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/templates/TemplateSelectViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetNavigationTest.kt
> DROID-3386 Primitives | Blank Template 

- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ResExtension.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Items.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/history/VersionHistoryViewModel.kt
> DROID-3515 Primitives | Wording update

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/EmptyStateWidgetScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
> DROID-3442 Widgets | Enhancement | Empty state

- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/slash/SlashExtensions.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetClicksTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetFilterTest.kt
> DROID-3341 Primitives | Editor, slash menu Properties

- app/src/main/java/com/anytypeio/anytype/ui/primitives/CreateTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/create/SetTypeTitlesAndIconScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/create/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HeaderScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/CreateObjectTypeViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
> DROID-3527 Primitives | Edit Type title screen

- gradle/libs.versions.toml
> DROID-3532 Protocol | Enhancement | MW 0.40.7

- app/src/main/java/com/anytypeio/anytype/di/feature/AllContentDI.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModel.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/presentation/AllContentViewModelFactory.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentTopToolbar.kt
> DROID-3426 All objects | Tabs Type and Relations removed

- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFieldsFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/WithSetScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/TypeScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HorizontalButtons.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
> DROID-3415 Primitives | The button "Properties" is hidden in the case of permissions

- app/src/main/java/com/anytypeio/anytype/ui/spaces/SpaceListFragment.kt
> DROID-3375 Settings | Fix | Update warning screens

- app/src/main/java/com/anytypeio/anytype/di/feature/PrimitivesObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/PropertiesDI.kt
- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/CreateTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/modals/ObjectSetSettingsFragment.kt
- app/src/main/res/navigation/graph.xml
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/dataview/SetDataViewProperties.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/VmFactory.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/EditTypePropertiesViewModel.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/VMFactory.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/MapperExtension.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/ObjectSetSettingsViewModel.kt
> DROID-3399 Primitives | Provide type relations into Type DataView properties menu

- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
> DROID-3485 Primitives | Layout note

- presentation/src/main/java/com/anytypeio/anytype/presentation/search/GlobalSearchViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetNavigationTest.kt
> DROID-3483 Global search | Filter type property meta in search

- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
> DROID-3462 Primitives | Update local properties after remove from Type command

- app/src/main/res/layout/fragment_object_menu.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/slash/holders/MainMenuHolder.kt
- core-ui/src/main/res/drawable/ic_properties_24.xml
- core-ui/src/main/res/drawable/ic_properties_purple_24.xml
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Items.kt
> DROID-3560 Primitives | New properties icon

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
> DROID-3555 Primitives | Show Types in the All Objects tab

- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/create/SetTypeTitlesAndIconScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectWrapperMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/value/object/ObjectValueViewModel.kt
> DROID-3484 Primitives | Create type screen, Auto-Populate Plural Field from Title

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/permissions/ObjectPermissions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/mapper/ObjectWrapperExtensionsKtTest.kt
> DROID-3409 Primitives | Refactor Object Layout Mapping Logic for Readability and Legacy Key Handling

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/slash/SlashPropertiesAdapter.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/slash/SlashWidget.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/slash/holders/MainMenuHolder.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/slash/holders/RelationsSubheaderMenuHolder.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/const/SlashConst.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/slash/SlashExtensions.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/slash/SlashItem.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/slash/SlashPropertyView.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetClicksTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/EditorSlashWidgetRelationsTest.kt
> DROID-3341 Primitives | Slash menu filters are updated

- app/build.gradle
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/AllContentWidget.kt
> DROID-3564 Widgets | Enhancement | DND improvements + remove legacy

- gradle/libs.versions.toml
> DROID-3233 App | Tech | Android framework lib updates

- app/build.gradle
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/AllContentWidget.kt
- core-ui/build.gradle
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewersWidget.kt
- gradle/libs.versions.toml
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- sample/build.gradle
> DROID-3564 App | Tech | DND improvements + remove legacy - Part 2

- core-ui/src/main/res/drawable/ic_properties_24.xml
> DROID-3560 Space settings | Icon update

- domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt
- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- feature-object-type/src/test/java/com/anytypeio/anytype/feature_object_type/TestFieldsMappping.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/relations/RelationListViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-3472 Primitives | Updating the logic for displaying properties for Template objects

- app/src/main/java/com/anytypeio/anytype/di/feature/PrimitivesObjectTypeDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/SpacePropertiesFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/SpaceTypesFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/fields/FieldsListScreen.kt
- core-ui/src/main/res/drawable/ic_arrow_right_18.xml
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/InfoScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/space/SpaceTypesListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/space/SpacePropertiesViewModel.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/space/ui/SpacePropertiesListScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/types/SpaceTypesViewModel.kt
> DROID-3571 Primitives | Space types and properties, sections ui

- localization/src/main/res/values/strings.xml
> DROID-3575 Primitives | Create object type, ui

- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-3572 Primitives | Type screen, set back new plus button

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/custom_icons/CiExtensionPuzzle.kt
> DROID-3575 Primitives | Create type screen, default icon updated

- gradle/libs.versions.toml
> DROID-3577 Protocol | Integrate MW 0.40.14

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentModels.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HeaderScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/TopToolbar.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-2905 Primitives | Fixes

- gradle/libs.versions.toml
> DROID-3582 Protocol | Mw 0.40.15

- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/primitives/WithSetScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/sets/ObjectSetFragment.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/fields/ui/ListScreen.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiEvent.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/HorizontalButtons.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
> DROID-3589 Type screen | Fix | Back navigation

- app/src/main/java/com/anytypeio/anytype/ui/widgets/SelectWidgetSourceFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/navigation/PageLinksAdapter.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/SelectWidgetSourceViewModel.kt
> DROID-3586 Widgets | Fix | Enhance search behavior to include suggested types and system widgets when selecting a source for widget

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3591 Protocol | Integrate 0.40.16

- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/ChatContainer.kt
- domain/src/test/java/com/anytypeio/anytype/domain/chats/ChatContainerTest.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/tools/DummyMessageGenerator.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
> DROID-2813 Chats | Tech | Basic pagination

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/ShimmerEffect.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/RelationValueListWidget.kt
- localization/src/main/res/values/strings.xml
> DROID-3541 Ui | Fix | Fix crash in ShimmerEffect due to invalid colorResource usage

- domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt
> DROID-3599 Widgets | Fix | Note snippet is missing from widget elements

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenToolbar.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/SpaceWidgetCard.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/Markup.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/TypeTemplatesWidget.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipResourcesExt.kt
> DROID-3601 App | Fix | Release 10 stabilization, part 1

- domain/src/main/java/com/anytypeio/anytype/domain/search/ObjectTypesSubscriptionManager.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/types/SpaceTypesViewModel.kt
> DROID-3601 Primitives | Tech | Storing archived types

- app/src/main/java/com/anytypeio/anytype/ui/primitives/ObjectTypeFragment.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/UiState.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/viewmodel/ObjectTypeViewModel.kt
- localization/src/main/res/values/strings.xml
> DROID-3593 Primitives | Fix | Disable type title update when restriction is present

- app/build.gradle
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/chats/Chat.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/AddChatMessage.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/ChatContainer.kt
- domain/src/test/java/com/anytypeio/anytype/domain/chats/ChatContainerTest.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
> DROID-2813 Chats | Enhancement | Infinite paging, first iteration

- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/allcontent/AllContentFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/base/NavigationRouter.kt
- app/src/main/java/com/anytypeio/anytype/ui/date/DateObjectFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/settings/RemoteFilesManageFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/collection/CollectionFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/navigation/AppNavigation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/editor/EditorViewModelTest.kt
> DROID-3601 Widgets | Fix | Fix missing args issue

- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/ListWidget.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/TreeWidget.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/ObjectIconCompose.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/BookmarkIconView.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/EmojiIconView.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/ImageIconView.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/TypeIconView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/objects/ObjectTypeExtensions.kt
> DROID-3612 Widgets | Icon fixes

- .github/workflows/build-release-apks-as-github-actions-artefacts.yml
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> DROID-3595 App | Tech | Update Github upload actions to v4

- app/src/main/java/com/anytypeio/anytype/di/main/EmojiModule.kt
- app/src/main/java/com/anytypeio/anytype/di/main/NotificationsModule.kt
- app/src/main/java/com/anytypeio/anytype/di/main/UtilModule.kt
- presentation/build.gradle
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/PushKeyProviderImpl.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/PushKeyProviderImplTest.kt
> DROID-3634 Notifications | Store pushKeyUpdates as Map

- .gitignore
> DROID-3645 Tech | Update gitignore

- app/src/main/java/com/anytypeio/anytype/di/main/NotificationsModule.kt
- core-models/build.gradle
- core-models/src/main/java/com/anytypeio/anytype/core_models/DecryptedPushContent.kt
- presentation/build.gradle
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/CryptoService.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/DecryptionPushContentService.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/CryptoServiceTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/DecryptionPushContentServiceImplTest.kt
> DROID-3638 Notifications | Push decryption, part 1

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/toolbar/ObjectTopToolbar.kt
> DROID-3652 Design | Design fixes

- app/src/main/java/com/anytypeio/anytype/device/AnytypePushService.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/notifications/PushDI.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/DecryptionPushContentServiceImplTest.kt
> DROID-3636 Notifications | Push display

- gradle/libs.versions.toml
> DROID-3594 Tech | AGP 8.10.0

- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/signup/OnboardingSoulCreationDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingNavigation.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingScreenContract.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingEmailScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingMnemonicPhraseScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingSetProfileNameScreen.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/OnBoardingColors.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/TypographyCompose.kt
- domain/src/main/java/com/anytypeio/anytype/domain/payments/SetMembershipEmail.kt
- domain/src/main/java/com/anytypeio/anytype/domain/resources/StringResourceProvider.kt
- localization/src/main/res/values/strings.xml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingSetProfileNameViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/util/StringResourceProviderImpl.kt
> DROID-3629 Onboarding | Email screen

- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/signup/OnboardingMnemonicDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/DataModule.kt
- app/src/main/java/com/anytypeio/anytype/di/main/NetworkModeModule.kt
- device/src/main/java/com/anytypeio/anytype/device/network_type/NetworkConnectionStatus.kt
- domain/src/main/java/com/anytypeio/anytype/domain/device/NetworkConnectionStatus.kt
- domain/src/main/java/com/anytypeio/anytype/domain/network/NetworkModeProvider.kt
- persistence/build.gradle
- persistence/src/main/java/com/anytypeio/anytype/persistence/networkmode/NetworkModeProvider.kt
- persistence/src/main/java/com/anytypeio/anytype/persistence/repo/DefaultAuthCache.kt
- persistence/src/test/java/com/anytypeio/anytype/persistence/DefaultAuthCacheTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModelTest.kt
> DROID-3629 Onboarding | Local mode status

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingEmailScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingSetProfileNameViewModel.kt
> DROID-3646 Onboarding | Email analytics

- core-models/src/main/java/com/anytypeio/anytype/core_models/LinkPreview.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/misc/GetLinkPreview.kt
- domain/src/main/java/com/anytypeio/anytype/domain/objects/CreateObjectFromUrl.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModelFactory.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBoxAttachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/Alias.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/bookmark/CreateBookmarkViewModel.kt
> DROID-3444 Chats | Enhancement | Bookmark flow updates

- app/src/main/java/com/anytypeio/anytype/ui/onboarding/Misc.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingMnemonicPhraseScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingWhatIsRecoveryPhraseScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-3629 Onboarding | Ui fixes

- gradle/libs.versions.toml
> DROID-3666 Protocol | Integrate 0.40.22

- analytics/src/main/java/com/anytypeio/anytype/analytics/features/WidgetAnalytics.kt
- app/src/main/java/com/anytypeio/anytype/navigation/Navigator.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Relations.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/multiplayer/Multiplayer.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/widgets/Widgets.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/navigation/PageLinksAdapter.kt
- domain/src/main/java/com/anytypeio/anytype/domain/multiplayer/SpaceViewSubscriptionContainer.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Toolbars.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/navigation/AppNavigation.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/SelectWidgetSourceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/Widget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/source/BundledWidgetSourceView.kt
> DROID-3662 Chats | Enhancement | Introduce system widget "Chat" + navigation changes

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-3678 Protocol | Integrate 0.41.0-rc7mobile

- app/src/main/java/com/anytypeio/anytype/device/AnytypePushService.kt
> DROID-3628 Chat | Push ui update

- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingEmailScreen.kt
> DROID-3671 Onboarding | Email screen, ui fix

- analytics/src/main/java/com/anytypeio/anytype/analytics/props/UserProperty.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ext/MembershipExt.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipConstants.kt
- core-ui/src/main/res/drawable/logo_new_explorer_64.xml
- core-ui/src/main/res/drawable/logo_new_explorer_96.xml
- core-ui/src/main/res/values-night/colors.xml
- core-ui/src/main/res/values/colors.xml
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierPreviewView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierScreen.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipViewModel.kt
- payments/src/test/java/com/anytypeio/anytype/payments/CocreatorActiveTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/MembershipTestsSetup.kt
- payments/src/test/java/com/anytypeio/anytype/payments/MembershipViewModelTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActiveAndFreeTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActivePurchasedOniOSTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierActiveWithDifferentSubIdTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActivePurchasedOniOS.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidBillingUnavailableTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierAndroidNotActiveTests.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierBuilderFallbackOnExplorerTest.kt
- payments/src/test/java/com/anytypeio/anytype/payments/TierConditionInfoTests.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
> DROID-3656 Membership | Support new tiers

- gradle/libs.versions.toml
> DROID-3685 Protocol | 0.41.0-rc8

- core-models/src/main/java/com/anytypeio/anytype/core_models/ext/MembershipExt.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/membership/MembershipConstants.kt
- payments/src/main/java/com/anytypeio/anytype/payments/mapping/MembershipExt.kt
- payments/src/main/java/com/anytypeio/anytype/payments/screens/TierPreviewView.kt
- payments/src/main/java/com/anytypeio/anytype/payments/viewmodel/MembershipViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/SpaceJoinRequestViewModel.kt
> DROID-3656 Payments | Legacy explorer tier

- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/RequestJoinSpaceFragment.kt
> DROID-3659 Multiplayer | Invite loading screen, dismiss

- app/src/main/java/com/anytypeio/anytype/device/AnytypePushService.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/DecryptionPushContentService.kt
> DROID-3628 Push | Json error fix

- app/src/main/java/com/anytypeio/anytype/device/AnytypePushService.kt
- app/src/main/java/com/anytypeio/anytype/device/NotificationBuilder.kt
- app/src/main/java/com/anytypeio/anytype/device/PushMessageProcessor.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/notifications/PushDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/NotificationsModule.kt
> DROID-3628 Notifications | Refactoring

- app/src/test/java/com/anytypeio/anytype/device/DefaultPushMessageProcessorTest.kt
> DROID-3628 Notifications | Tests

- gradle/libs.versions.toml
> DROID-3688 Protocol | 0.41.0-rc9

- app/src/main/java/com/anytypeio/anytype/device/AnytypePushService.kt
- app/src/main/java/com/anytypeio/anytype/device/NotificationBuilder.kt
- app/src/main/java/com/anytypeio/anytype/device/NotificationExtensions.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/notifications/PushDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/main/MainActivity.kt
- app/src/test/java/com/anytypeio/anytype/device/DefaultPushMessageProcessorTest.kt
- app/src/test/java/com/anytypeio/anytype/device/NotificationExtensionsTest.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/DecryptedPushContent.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/Extensions.kt
- localization/src/main/res/values/strings.xml
- presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/DecryptionPushContentServiceImplTest.kt
> DROID-3690 Notifications | Fixes, part 1

- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetDocumentImageIcon.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetImageIcon.kt
- domain/src/main/java/com/anytypeio/anytype/domain/icon/SetTextBlockImage.kt
- domain/src/main/java/com/anytypeio/anytype/domain/media/UploadFile.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/account/ProfileSettingsViewModel.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/NewSettings.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
> DROID-2966 Chat | Fix | Misc. fixes

- gradle/libs.versions.toml
> DROID-3691 Protocol | 0.41.0-rc10

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
> DROID-3590 Vault | Space counters, turn off mentions

- crowdin.yml
---
---
This PR adds Japanese language code `ja` to the crowdin.yml file.
Hello Anytype team,
The Japanese translation on Crowdin is almost complete.
Thank you for developing such amazing apps!
> l10n | Enable Japanese translation

- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/Widget.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/splash/SplashViewModelTest.kt
- test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/DataView.kt
> DROID-3362 Widgets | Fix | Should not trigger container creation on irrelevant keys updates

- app/src/main/java/com/anytypeio/anytype/app/Notifications.kt
- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/RequestJoinSpaceFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Notification.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/RequestJoinSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/NotificationsViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModelTest.kt
> DROID-3703 Invite | Join without approve link, success notification

- app/src/main/java/com/anytypeio/anytype/ui/spaces/CreateSpaceFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/spaces/CreateSpaceScreen.kt
> DROID-3446 Vault | New space or chat creation flow, part 2

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultSpaceCard.kt
> DROID-3590 Vault 2.0 | Cards ui

- gradle/libs.versions.toml
> DROID-3724 Protocol | Enhancement | MW 0.41.0-rc17

- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatFragment.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/IOExt.kt
- feature-chats/build.gradle
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Attachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBoxAttachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBubble.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- feature-chats/src/main/res/drawable/ic_chat_attachment_play.xml
- gradle/libs.versions.toml
> DROID-2966 Chats | Enhancement | Displaying video thumbnail + Request playing video by OS media player (MVP)

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreenPreview.kt
> DROID-3626 Space chat | Compose previews

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Attachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Gallery.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Reactions.kt
> DROID-2966 Chats | Fix | Misc. UI imporvements

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/tools/Media.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBoxAttachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-3047 Chats | Enhancement | Allow capturing and sending video 

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultSpaceCard.kt
- gradle/libs.versions.toml
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Models.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
> DROID-3318 Vault 2.0 | Unread section

- app/src/main/java/com/anytypeio/anytype/app/Notifications.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Notification.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/RequestJoinSpaceViewModel.kt
> DROID-3708 Multiplayer | After space join notification

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatView.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Toolbars.kt
> DROID-3742 Chats | Enhancement | Add floating date header

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBubble.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
> DROID-3739 Chats | Enhancement | Swipe-to-reply fixes

- app/src/main/java/com/anytypeio/anytype/ext/FragmentResultContract.kt
- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultSpaceCard.kt
- app/src/main/res/layout/fragment_editor.xml
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/Toolbars.kt
- domain/src/main/java/com/anytypeio/anytype/domain/object/GetObject.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModelFactory.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/Attachments.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatPreviews.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
> DROID-3741 Chats | Enhancement | Create object via chat box

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Models.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
> DROID-3590 Vault 2.0 | Top toolbar + loading state

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/test/java/com/anytypeio/anytype/ui/editor/EditorFragmentTextSelectionTest.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/extensions/ViewExtension.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/BlockAdapter.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/TextBlockHolder.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/interface/TextHolder.kt
- core-ui/src/test/java/com/anytypeio/anytype/core_ui/features/editor/BlockAdapterTextSelectionValidationTest.kt
- core-ui/src/test/java/com/anytypeio/anytype/core_ui/features/editor/Droid3763EdgeCasesTest.kt
- core-ui/src/test/java/com/anytypeio/anytype/core_ui/features/editor/holders/TextHolderCursorValidationTest.kt
> DROID-3763 App | Sentry fixes

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
> DROID-3748 Chats | Fix | Crash on empty chat

- app/src/main/java/com/anytypeio/anytype/ui/spaces/CreateSpaceScreen.kt
> DROID-3719 Space | Design | Create space, ui fixes

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/syncstatus/StatusBadge.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/BookmarkIconView.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/objectIcon/TypeIconView.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/header/TopToolbar.kt
- feature-object-type/src/main/java/com/anytypeio/anytype/feature_object_type/ui/space/SpaceTypesListScreen.kt
- feature-properties/src/main/java/com/anytypeio/anytype/feature_properties/space/ui/SpacePropertiesListScreen.kt
> DROID-3664 Design | Fix | Bookmark icons etc.

- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
> DROID-3780 | Fix | Pasted email address parsed as URL in chat messages

- .github/workflows/check.yml
> CI | Fix unit tests, update check

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectCreateTest.kt
> DROID-3804 Tech | ObjectWrapper, refactoring

- app/build.gradle
- app/src/main/java/com/anytypeio/anytype/app/AndroidApplication.kt
- gradle/libs.versions.toml
> DROID-3737 Tech | Coil, support cache-control

- app/src/main/java/com/anytypeio/anytype/app/AndroidApplication.kt
> DROID-3810 Analytics | Amplitude session setup

- gradle/libs.versions.toml
> DROID-3826 Protocol | Integrate 0.42.0-rc11

- gradle/libs.versions.toml
- protocol/src/main/proto/events.proto
- protocol/src/main/proto/models.proto
> DROID-3833 Protocol | Integrate v0.42.0-rc14

- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/ShareSpaceScreen.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
> DROID-3762 Members list | Don't show members in removing status

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultEmptyScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/foundation/SearchBar.kt
- localization/src/main/res/values/strings.xml
> DROID-3788 Vault 2.0 | Spaces search

- core-models/src/main/java/com/anytypeio/anytype/core_models/Event.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/ChatPreviewContainer.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/MiddlewareEventMapper.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/events/ChatEventMiddlewareChannel.kt
> DROID-3841 Chats | Fix | Chat preview subscription fixes

- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/dv/ViewerEditWidget.kt
> DROID-3204 Query | Fix | Viewer title updated

- app/src/main/java/com/anytypeio/anytype/di/feature/home/HomescreenDI.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/vault/VaultDI.kt
- app/src/main/java/com/anytypeio/anytype/di/main/SubscriptionsModule.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/ChatContainer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/ChatPreviewContainer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/SpaceChatPreviewContainer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/chats/VaultChatPreviewContainer.kt
- domain/src/main/java/com/anytypeio/anytype/domain/subscriptions/GlobalSubscriptionManager.kt
- domain/src/test/java/com/anytypeio/anytype/domain/chats/ChatPreviewContainerTest.kt
- domain/src/test/java/com/anytypeio/anytype/domain/chats/SpaceLevelChatPreviewContainerTest.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Factory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/SpaceChatWidgetContainer.kt
> DROID-3309 Vault | Chat preview, updated

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3857 Protocol | Integrate v0.42.0-rc20

- gradle/libs.versions.toml
> DROID-3858 Protocol | Integrate v0.42.0-rc21

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt
- data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt
- domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt
- domain/src/main/java/com/anytypeio/anytype/domain/vault/SetSpaceOrder.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/vault/VaultViewModelFabric.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/vault/VaultViewModelTest.kt
> DROID-3819 Vault 2 | First space loading + mw space set order 

- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/media/MediaActivity.kt
- core-ui/build.gradle
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/BlockAdapter.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/editor/holders/other/Title.kt
- core-ui/src/main/res/layout/item_block_title_video.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/Command.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/editor/listener/ListenerType.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/mapper/ObjectIconMapper.kt
> DROID-2966 Editor | Enhancement | Allow playing audio or video objects by in-app media player

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
> DROID-3835 Vault 2.0 | Hiding dropdown menus during drag operations

- presentation/src/main/java/com/anytypeio/anytype/presentation/settings/DebugViewModel.kt
> DROID-3794 Debug screen | Error handling for the "read all messages"

- gradle/libs.versions.toml
> DROID-3877 Protocol | Integrate 0.42.0-rc29

- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreenAlertModals.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatBox.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/ui/ChatScreen.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Models.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
> DROID-3866 Chat | Camera permission handling

- gradle/libs.versions.toml
- protocol/src/main/proto/models.proto
> DROID-3886 Protocol | Integrate MW 0.42.0-rc30

- app/gradle.properties
> DROID-3710 App | Tech | Bump version (0.40.0)

- app/src/main/java/com/anytypeio/anytype/di/feature/MoveToDi.kt
- app/src/main/java/com/anytypeio/anytype/ui/editor/EditorFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/editor/EditorViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/moving/MoveToViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/moving/MoveToViewModelFactory.kt
> DROID-3897 App | Pre-release sentry fixes

- presentation/build.gradle
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
> DROID-3878 Vault | Hide mute for shared spaces

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultScreenPreview.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultSpaceActions.kt
- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultSpaceCard.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- domain/src/main/java/com/anytypeio/anytype/domain/resources/StringResourceProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/CreateSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/util/StringResourceProviderImpl.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Models.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/vault/VaultViewModelTest.kt
> DROID-3905 Vault | Proper space type differentiation

- gradle/libs.versions.toml
> DROID-3906 Protocol | Integrate 0.42.1

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/workspace/WorkspaceManager.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Factory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/vault/VaultViewModelFabric.kt
> DROID-3772 Navigation | Get rid of legacy isChatAllowed logic, clear space manager

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/vault/VaultViewModelTest.kt
> DROID-3895 Vault 2.0 | Analytics, pin | unpin events

- feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/models/AllContentSearchParams.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/search/ObjectSearchConstants.kt
> DROID-3915 All objects | Filter by chats in Lists

- analytics/src/main/java/com/anytypeio/anytype/analytics/base/EventsDictionary.kt
- app/src/main/java/com/anytypeio/anytype/di/feature/onboarding/signup/OnboardingMnemonicDI.kt
- app/src/main/java/com/anytypeio/anytype/ui/multiplayer/ShareSpaceFragment.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/SelectAccount.kt
- localization/src/main/res/values/strings.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/ShareSpaceViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/OnboardingStartViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/login/OnboardingMnemonicLoginViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingSetProfileNameViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingMnemonicViewModelTest.kt
> DROID-3919 Onboarding | Update analytics

- gradle/libs.versions.toml
> DROID-3918 Protocol | Integrate 0.42.2

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/Factory.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/vault/VaultViewModelFabric.kt
> DROID-3922 Navigation | Update back navigation and space clearing

- gradle/libs.versions.toml
> DROID-3924 Protocol | Integrate 0.42.3

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3925 Protocol | Integrate 0.43.0-rc01

- app/gradle.properties
> DROID-3878 Tech | Bump version 0.39.29

- app/src/test/java/com/anytypeio/anytype/MarkupExtractTest.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/common/Markup.kt
- core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/text/MentionSpanExt.kt
- core-ui/src/test/java/com/anytypeio/anytype/core_ui/extensions/EmojiUtilsTest.kt
> DROID-3927 Editor | Support emoji markup in multi-line text

- gradle/libs.versions.toml
> DROID-3929 Protocol | Integrate 0.42.4

- app/src/main/java/com/anytypeio/anytype/ui/chats/ChatFragment.kt
- core-utils/src/main/java/com/anytypeio/anytype/core_utils/intents/SystemAction.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/presentation/ChatViewModel.kt
- feature-chats/src/main/java/com/anytypeio/anytype/feature_chats/tools/LinkDetector.kt
- feature-chats/src/test/java/com/anytypeio/anytype/feature_chats/tools/LinkDetectorTest.kt
> DROID-3848 Chats | Clickable links functionality for emails, phone numbers, and URLs in chat messages

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3933 Protocol | Integrate v0.43.0-rc02

- app/src/main/java/com/anytypeio/anytype/ui/onboarding/OnboardingScreenContract.kt
- app/src/main/java/com/anytypeio/anytype/ui/splash/PulsatingCircleScreen.kt
- localization/src/main/res/values/strings.xml
> DROID-3935 Onboarding | Ui | Spalsh screen, bottom text

- analytics/src/main/java/com/anytypeio/anytype/analytics/props/UserProperty.kt
- analytics/src/main/java/com/anytypeio/anytype/analytics/tracker/AmplitudeTracker.kt
- domain/src/main/java/com/anytypeio/anytype/domain/auth/interactor/LaunchAccount.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/extension/AnalyticsExt.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/main/MainViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/OnboardingStartViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/onboarding/signup/OnboardingEmailAndSelectionViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt
- presentation/src/test/java/com/anytypeio/anytype/presentation/splash/SplashViewModelTest.kt
> DROID-3947 Analytics | Network id

- core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/spaces/SpaceSettingsViewModel.kt
> DROID-3761 Space | Show Notifications option only for shared spaces

- gradle/libs.versions.toml
- protocol/src/main/proto/commands.proto
> DROID-3966 Protocol | Integrate v0.44.0-rc02

- app/src/main/java/com/anytypeio/anytype/ui/publishtoweb/PublishToWebScreen.kt
- feature-ui-settings/src/main/java/com/anytypeio/anytype/ui_settings/space/new_settings/Items.kt
- localization/src/main/res/values/strings.xml
> DROID-3955 Web Publishing | Fix | Overlap name field

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreenFragment.kt
- core-models/src/main/java/com/anytypeio/anytype/core_models/Event.kt
- gradle/libs.versions.toml
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/MiddlewareEventChannel.kt
- middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/MiddlewareEventMapper.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- protocol/src/main/proto/events.proto
> DROID-3990 Protocol | Integrate 0.44.0-rc05

- gradle/libs.versions.toml
> DROID-4001 Protocol | Integrate 0.44.0-rc06

- domain/src/main/java/com/anytypeio/anytype/domain/object/SpaceViewExt.kt
- domain/src/test/java/com/anytypeio/anytype/domain/object/SpaceViewExtKtTest.kt
> DROID-3995 Invites | Remove limits for chats

- app/src/main/java/com/anytypeio/anytype/ui/vault/VaultChatCard.kt
- device/src/main/java/com/anytypeio/anytype/device/providers/DateProviderImpl.kt
- device/src/test/java/com/anytypeio/anytype/DateProviderImplTest.kt
- domain/src/main/java/com/anytypeio/anytype/domain/resources/StringResourceProvider.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/util/StringResourceProviderImpl.kt
> DROID-3960 Vault 2.0 | The date format in the vault chat preview

- app/src/main/AndroidManifest.xml
> DROID-3974 App | Set back camera permission

- gradle/libs.versions.toml
> DROID-4039 Protocol | Integrate 0.44.0

- gradle/libs.versions.toml
> DROID-4043 Protocol | Integrate 0.44.1

- gradle/libs.versions.toml
> DROID-4049 Protocol | Integrate 0.44.2

- app/src/main/java/com/anytypeio/anytype/ui/home/HomeScreen.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/menu/WidgetDropDownMenu.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/BinWidgetCard.kt
- app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/Widget.kt
> DROID-4045 Widgets | Diff fixes

- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
> DROID-4045 Widgets | Collapsed state by sections

- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
> DROID-4045 Widgets | Expanded states, kdoc

- app/src/main/java/com/anytypeio/anytype/ui/widgets/menu/WidgetDropDownMenu.kt
- core-utils/src/main/res/values-night/colors.xml
- core-utils/src/main/res/values/colors.xml
- presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt
- presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/Widget.kt
> DROID-4016 Widgets | Data Space chat widget

- gradle/libs.versions.toml
> DROID-4055 Protocol | Integrate v0.44.3

- app/src/main/java/com/anytypeio/anytype/ui/onboarding/screens/signup/OnboardingEmailScreen.kt
> DROID-4010 Onboarding | Email screen placeholder

- gradle/libs.versions.toml
> DROID-4060 Protocol | Integrate 0.44.4
