anyproto/anytype-kotlin

app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt, app/src/main/java/com/anytypeio/anytype/di/feature/ObjectSetDI.kt, core-models/src/main/java/com/anytypeio/anytype/core_models/Block.kt, domain/src/main/java/com/anytypeio/anytype/domain/dataview/interactor/CreateDataViewObject.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToCoreModelMappers.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetExtension.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetViewModel.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/sets/state/ObjectState.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/sets/viewer/ViewerView.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/templates/ObjectTypeTemplatesContainer.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/collections/CollectionTemplatesDelegateTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/collections/MockSet.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectCreateTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateCollectionViewTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/collections/ObjectStateSetViewTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/sets/ObjectSetReducerTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/sets/ObjectSetTemplatesMenuTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/sets/ViewerDefaultObjectTypeTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/ObjectSetViewModelTestSetup.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/sets/main/SetByRelationTest.kt, test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/DataView.kt
- To create an object in the Collection, the type is now taken from the View; in case it is absent, the Page type is used.
- To create an object in the Set by relation, the type is now taken from the View; in case it is absent, the Page type is used.
- To create an object in the Set by type, the type is taken from the Set query
=> DROID-1620 Collection | Enhancement | View's default object type

presentation/src/main/java/com/anytypeio/anytype/presentation/library/LibraryViewModel.kt
Fixing crash:
```
Key "rel-XXXXXX" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
```
=> DROID-1750 Library | Fix | Ensuring unique keys for lazy column to prevent crash in the library component

core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt, domain/src/test/java/com/anytypeio/anytype/domain/misc/GetObjectTypeTest.kt
=> DROID-1984 Protocol  | Fix | Type source object as list

app/src/main/java/com/anytypeio/anytype/ui/templates/EditorTemplateFragment.kt
=> DROID-2055 Templates | Fix | Different background color and menu in dark

core-ui/src/main/java/com/anytypeio/anytype/core_ui/widgets/FeaturedRelationGroupWidget.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/sets/ObjectSetExtension.kt
=> DROID-2058 Relations | Object type is not displayed first of featured relations

presentation/src/test/java/com/anytypeio/anytype/presentation/objects/CreateDVObjectTest.kt
=> DROID-1865 Object create | Prefilled relations, tests

presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt
Limits for tree widgets are only enforced at the root level for bundled widgets. For widgets using a custom object as their source, these limits are not enforced at the root level.
=> DROID-2613 Widgets | Fix | Fix limit for tree widgets with custom source

feature-all-content/src/main/java/com/anytypeio/anytype/feature_allcontent/ui/AllContentScreen.kt
=> DROID-2930 All content | Empty State Is Not Centered When the Keyboard Is Open

core-models/src/main/java/com/anytypeio/anytype/core_models/Command.kt, core-models/src/main/java/com/anytypeio/anytype/core_models/chats/Chat.kt, data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt, data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt, domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt, domain/src/main/java/com/anytypeio/anytype/domain/chats/ChatContainer.kt, domain/src/main/java/com/anytypeio/anytype/domain/chats/GetChatMessagesByIds.kt, feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionView.kt, feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionViewModel.kt, feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/presentation/DiscussionViewModelFactory.kt, feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionPreviews.kt, feature-discussions/src/main/java/com/anytypeio/anytype/feature_discussions/ui/DiscussionScreen.kt, feature-discussions/src/main/res/drawable/ic_chat_close_chat_box_reply.xml, localization/src/main/res/values/strings.xml, middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
=> DROID-3044 Chats | Enhancement | Basics for chat replies

app/src/androidTest/java/com/anytypeio/anytype/features/sets/dv/TestObjectSetSetup.kt, app/src/main/java/com/anytypeio/anytype/di/feature/home/HomescreenDI.kt, app/src/main/java/com/anytypeio/anytype/di/main/UtilModule.kt, core-models/src/main/java/com/anytypeio/anytype/core_models/Constants.kt, device/src/main/java/com/anytypeio/anytype/device/providers/AppDefaultDateFormatProvider.kt, device/src/main/java/com/anytypeio/anytype/device/providers/DateProviderImpl.kt, device/src/test/java/com/anytypeio/anytype/DateProviderImplTest.kt, domain/src/main/java/com/anytypeio/anytype/domain/misc/DateProvider.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModel.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/DataViewListWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/LinkWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/home/HomeScreenViewModelTest.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/home/TreeWidgetContainerTest.kt
=> DROID-3105 Widgets | Tech | Using field parser to get object name

app/src/main/java/com/anytypeio/anytype/ui/widgets/types/DataViewWidget.kt, app/src/main/java/com/anytypeio/anytype/ui/widgets/types/LinkWidget.kt, app/src/main/java/com/anytypeio/anytype/ui/widgets/types/ListWidget.kt, app/src/main/java/com/anytypeio/anytype/ui/widgets/types/TreeWidget.kt, app/src/main/java/com/anytypeio/anytype/ui/widgets/types/Widget.kt, domain/src/main/java/com/anytypeio/anytype/domain/primitives/FieldParser.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/LinkWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/ListWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/TreeWidgetContainer.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/Widget.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/widgets/WidgetView.kt
=> DROID-2797 Date as an object | Support relative dates in widgets

feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/SearchParams.kt
=> DROID-3167 Date as an Object | Exclude all object which were not created by space members

app/src/main/java/com/anytypeio/anytype/di/main/NetworkModeModule.kt, app/src/main/java/com/anytypeio/anytype/di/main/SubscriptionsModule.kt, core-models/src/main/java/com/anytypeio/anytype/core_models/DeviceNetworkType.kt, data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockDataRepository.kt, data/src/main/java/com/anytypeio/anytype/data/auth/repo/block/BlockRemote.kt, device/src/main/AndroidManifest.xml, device/src/main/java/com/anytypeio/anytype/device/network_type/NetworkConnectionStatus.kt, domain/src/main/java/com/anytypeio/anytype/domain/block/repo/BlockRepository.kt, domain/src/main/java/com/anytypeio/anytype/domain/device/NetworkConnectionStatus.kt, domain/src/main/java/com/anytypeio/anytype/domain/subscriptions/GlobalSubscriptionManager.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/block/BlockMiddleware.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/Middleware.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/Alias.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/mappers/ToMiddlewareModelMappers.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareService.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/service/MiddlewareServiceImplementation.kt
=> DROID-2831 Tech | Implement Device.Network.State.Set

app/src/main/java/com/anytypeio/anytype/di/feature/DateObjectDI.kt, app/src/main/java/com/anytypeio/anytype/ui/date/DateObjectFragment.kt, domain/src/main/java/com/anytypeio/anytype/domain/objects/StoreOfRelations.kt, domain/src/test/java/com/anytypeio/anytype/domain/misc/DefaultRelationsStoreTest.kt, feature-date/src/main/java/com/anytypeio/anytype/feature_date/mapping/DateObjectModelsExt.kt, feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectVMFactory.kt, feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/DateObjectViewModel.kt, feature-date/src/main/java/com/anytypeio/anytype/feature_date/viewmodel/SearchParams.kt, feature-date/src/test/java/com/anytypeio/anytype/feature_date/DateObjectViewModelTest.kt, feature-date/src/test/java/com/anytypeio/anytype/feature_date/DefaultCoroutineTestRule.kt
=> DROID-2793 Date as an Object | Tech | Observe relations store

presentation/src/main/java/com/anytypeio/anytype/presentation/editor/render/DefaultBlockViewRenderer.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/editor/DefaultBlockViewRendererTest.kt
=> DROID-3185 File layout | Hide file block

presentation/src/test/java/com/anytypeio/anytype/presentation/editor/editor/file_layout/FileLayoutTest.kt
=> DROID-2898 File as Object | New layout ui, tests

app/src/main/java/com/anytypeio/anytype/di/main/DataModule.kt, app/src/main/java/com/anytypeio/anytype/security/KeystoreManager.kt
🧠 Summary
This PR refactors the initialization and recovery logic for EncryptedSharedPreferences by introducing a centralized KeystoreManager class.
✅ What’s Changed
•	Added KeystoreManager to encapsulate:
•	EncryptedSharedPreferences creation
•	Keystore corruption detection (InvalidKeyBlob)
•	Safe key deletion and recovery
•	Replaced raw @Provides block in DataModule with a call to KeystoreManager.initializeEncryptedPreferences()
•	Removed redundant initializeEncryptedPrefs() and retryInstantiatingEncryptedPrefs() methods
•	Hardcoded the correct internal key alias (_androidx_security_master_key_) used by MasterKeys.getOrCreate(...), based on source code review
•	Scoped recovery only to known keystore corruption errors, avoiding unnecessary data loss
•	Ensured compatibility with API 33+ …
=> DROID-3609 Auth | Fix | Centralize EncryptedSharedPreferences Initialization in KeystoreManager

core-models/src/main/java/com/anytypeio/anytype/core_models/ObjectWrapper.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/splash/SplashViewModel.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/splash/SplashViewModelTest.kt, test/core-models-stub/src/main/java/com/anytypeio/anytype/core_models/DataView.kt
•	Added timeout when restoring the last opened space:
•	If the spaceViews.observe() does not emit a valid view within 5 seconds, fallback behavior is triggered.
•	Logged warnings:
•	When the observed space view remains in an unknown status, a warning (Timber.w) is now emitted.
•	When a timeout occurs, a warning is logged to indicate that navigation fallback was triggered.
•	Improved restoration logic:
•	Now we proceed to open the last object (navigate to widgets or space chat) even if the space view is still in a loading state.
•	This ensures a faster and smoother restoration experience without forcing the user to wait for the full space loading.
Previously, restoration was blocked until the space view fully loaded, potentially causing a long wait or even blocking navigation if there were …
=> DROID-3611 Navigation | Fix | Allow restoration of last opened space from loading state on splash screen - Hotfix

app/src/main/java/com/anytypeio/anytype/di/main/NotificationsModule.kt, core-models/src/main/java/com/anytypeio/anytype/core_models/chats/PushKeyUpdate.kt, data/src/main/java/com/anytypeio/anytype/data/auth/event/PushKeyRemoteChannel.kt, domain/src/main/java/com/anytypeio/anytype/domain/chats/PushKeyChannel.kt, middleware/src/main/java/com/anytypeio/anytype/middleware/interactor/events/PushKeyMiddlewareChannel.kt, middleware/src/test/java/com/anytypeio/anytype/middleware/interactor/PushKeyMiddlewareChannelTest.kt, presentation/src/main/java/com/anytypeio/anytype/presentation/notifications/PushKeyProviderImpl.kt, presentation/src/test/java/com/anytypeio/anytype/presentation/notifications/PushKeyProviderImplTest.kt
=> DROID-3634 Notifications | Handle pushKeyUpdates and store

app/src/main/java/com/anytypeio/anytype/ui/multiplayer/RequestJoinSpaceFragment.kt, core-ui/src/main/java/com/anytypeio/anytype/core_ui/features/multiplayer/Joining.kt, localization/src/main/res/values/strings.xml, presentation/src/main/java/com/anytypeio/anytype/presentation/multiplayer/RequestJoinSpaceViewModel.kt
=> DROID-3659 Multiplayer | Support link without approve, fixes

app/src/main/java/com/anytypeio/anytype/device/NotificationBuilder.kt, core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/OnBoardingTypographyCompose.kt, core-ui/src/main/java/com/anytypeio/anytype/core_ui/views/TypographyCompose.kt
=> DROID-3704 Sentry | Release 11

app/src/main/java/com/anytypeio/anytype/ui/multiplayer/RequestJoinSpaceFragment.kt, app/src/test/java/com/anytypeio/anytype/ui/multiplayer/RequestJoinSpaceFragmentSafeDismissTest.kt
=> DROID-3763 App | Fix | Safe dismiss request to join screen

presentation/src/main/java/com/anytypeio/anytype/presentation/vault/VaultViewModel.kt
=> DROID-3909 Vault | Hiding red dot in release 12
